<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Novolis.Time.Unit</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Novolis.Time\Novolis.Time.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Time.Week\Novolis.Time.Week.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Time.Month\Novolis.Time.Month.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Time.Workday\Novolis.Time.Workday.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Time.Worktime\Novolis.Time.Worktime.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Time.Worktime.Legal\Novolis.Time.Worktime.Legal.csproj" />
  </ItemGroup>
</Project>
