<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>GeneratePublicHolidays</RootNamespace>
    <IsPackable>false</IsPackable>
    <NovolisStackAnalyzers>false</NovolisStackAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PublicHoliday" />
    <LibraryReference Include="Novolis.CodeGen.Reflection.Dump" />
    <ProjectReference Include="..\..\src\Novolis.Time.Workday\Novolis.Time.Workday.csproj" />
  </ItemGroup>
</Project>
