using GeneratePublicHolidays;
using Novolis.CodeGen.Reflection.Dump;
using Novolis.Time.Workday;
using PublicHoliday;

const int yearCount = 6;
var firstYear = DateTime.UtcNow.Year;
var lastYear = firstYear + yearCount - 1;
var years = Enumerable.Range(firstYear, yearCount).ToArray();
var outputDirectory = args.Length > 0
    ? Path.GetFullPath(args[0])
    : Path.GetFullPath(Path.Combine(
        AppContext.BaseDirectory,
        "..",
        "..",
        "..",
        "..",
        "..",
        "src",
        "Novolis.Time.Workday",
        "Calendars"));

var packageVersion = typeof(PublicHolidayFactory).Assembly.GetName().Version?.ToString() ?? "unknown";
var dumpOptions = new VarDump.Visitor.DumpOptions
{
    GenerateVariableInitializer = true,
    UseNamedArgumentsInConstructors = true,
    IgnoreDefaultValues = false,
    IgnoreNullValues = true,
};

Directory.CreateDirectory(outputDirectory);
foreach (var location in LocationSelection.Selected)
{
    var facts = LoadFacts(location.CountryCode, years);
    var expression = ExtractExpression(facts.DumpVar(dumpOptions));
    var source = RenderLocation(location, firstYear, lastYear, packageVersion, expression);
    var path = Path.Combine(outputDirectory, $"{location.TypeName}.cs");
    await File.WriteAllTextAsync(path, source);
    Console.WriteLine($"Wrote {path}");
}

var catalogPath = Path.Combine(outputDirectory, "CalendarCatalog.cs");
await File.WriteAllTextAsync(catalogPath, RenderCatalog(LocationSelection.Selected, firstYear, lastYear));
Console.WriteLine($"Wrote {catalogPath}");

var sourcePath = Path.Combine(outputDirectory, "GeneratedCalendarSource.cs");
await File.WriteAllTextAsync(sourcePath, RenderSource(packageVersion, firstYear, lastYear));
Console.WriteLine($"Wrote {sourcePath}");

static List<PublicHolidayFact> LoadFacts(string countryCode, int[] years)
{
    var provider = PublicHolidayFactory.GetPublicHolidayForCountry(countryCode);
    return years
        .SelectMany(year => provider.PublicHolidayNames(year))
        .Select(pair => new PublicHolidayFact(
            DateOnly.FromDateTime(pair.Key),
            string.IsNullOrWhiteSpace(pair.Value) ? "Public holiday" : pair.Value))
        .GroupBy(holiday => holiday.Date)
        .Select(group => group.First())
        .OrderBy(holiday => holiday.Date)
        .ToList();
}

static string ExtractExpression(string dumped)
{
    var trimmed = dumped.Trim();
    var equals = trimmed.IndexOf('=');
    if (equals < 0)
    {
        throw new InvalidOperationException("VarDump did not emit a variable initializer.");
    }

    return trimmed[(equals + 1)..].Trim().TrimEnd(';').Trim();
}

static string RenderLocation(
    LocationSelection location,
    int firstYear,
    int lastYear,
    string packageVersion,
    string expression)
{
    var lines = expression.Split('\n').Select(line => line.TrimEnd('\r')).ToArray();
    var minimumIndent = lines
        .Where(line => line.Trim().Length > 0)
        .Select(line => line.TakeWhile(char.IsWhiteSpace).Count())
        .DefaultIfEmpty(0)
        .Min();
    var indented = string.Join(
        Environment.NewLine,
        lines.Select(line => string.IsNullOrWhiteSpace(line) ? string.Empty : "        " + line[minimumIndent..]));

    return $$"""
        // <auto-generated>
        // Baseline holiday rules for {{location.DisplayName}}. Regenerated by tools/GeneratePublicHolidays.
        // Source: PublicHoliday {{packageVersion}}. Years {{firstYear}} through {{lastYear}}.
        // </auto-generated>

        namespace Novolis.Time.Workday;

        /// <summary>
        /// Baseline public-holiday rules for {{location.DisplayName}} (<c>{{location.CountryCode}}</c>),
        /// {{firstYear}} through {{lastYear}}.
        /// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
        /// without rewriting the rest of the collection.
        /// </summary>
        public static class {{location.TypeName}}
        {
            /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
            public const string CountryCode = "{{location.CountryCode}}";

            /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
            public const int FirstYear = {{firstYear}};

            /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
            public const int LastYear = {{lastYear}};

            /// <summary>
            /// Baseline holiday rules for {{location.DisplayName}}, {{firstYear}} through {{lastYear}}.
            /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
            /// </summary>
            public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        {{indented}};
        }

        """;
}

static string RenderCatalog(IReadOnlyList<LocationSelection> locations, int firstYear, int lastYear)
{
    var cases = string.Join(
        Environment.NewLine,
        locations.Select(location =>
            $"            {location.TypeName}.CountryCode => {location.TypeName}.Baseline,"));

    return $$"""
        // <auto-generated>
        // Index of in-code calendar baselines. Regenerated by tools/GeneratePublicHolidays.
        // </auto-generated>

        namespace Novolis.Time.Workday;

        /// <summary>
        /// In-code calendar baselines for the selected locations, {{firstYear}} through {{lastYear}}.
        /// Each collection is a default. Sparse configuration overrides individual dates.
        /// </summary>
        public static class CalendarCatalog
        {
            /// <summary>First calendar year present in every baseline.</summary>
            public const int FirstYear = {{firstYear}};

            /// <summary>Last calendar year present in every baseline.</summary>
            public const int LastYear = {{lastYear}};

            /// <summary>ISO country codes that have a generated baseline.</summary>
            public static IReadOnlyList<string> CountryCodes { get; } =
            [
        {{string.Join(Environment.NewLine, locations.Select(location => $"        {location.TypeName}.CountryCode,"))}}
            ];

            /// <summary>Returns the baseline holiday rules for a selected location.</summary>
            public static IReadOnlyList<PublicHolidayFact> GetBaseline(string countryCode)
            {
                ArgumentException.ThrowIfNullOrWhiteSpace(countryCode);
                return countryCode.ToUpperInvariant() switch
                {
        {{cases}}
                    _ => throw new InvalidOperationException(
                        $"No generated calendar baseline exists for {countryCode}. Regenerate with the private GeneratePublicHolidays tool."),
                };
            }
        }

        """;
}

static string RenderSource(string packageVersion, int firstYear, int lastYear) =>
    $$"""
    // <auto-generated>
    // Source identity recorded with the in-code calendar baselines.
    // </auto-generated>

    namespace Novolis.Time.Workday;

    /// <summary>
    /// Source identity for the generated calendar baselines covering {{firstYear}} through {{lastYear}}.
    /// </summary>
    public static class GeneratedCalendarSource
    {
        /// <summary>Package that supplied the holiday rules.</summary>
        public const string Package = "PublicHoliday";

        /// <summary>Package version recorded at generation.</summary>
        public const string PackageVersion = "{{packageVersion}}";

        /// <summary>Generator revision that wrote the baselines.</summary>
        public const string GeneratorVersion = "novolis-time-holiday-generator-2";
    }

    """;
