<Project>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CS1591;CS1573;CS1574</NoWarn>
  </PropertyGroup>
  <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props" />
  <Import Project="$(MSBuildThisFileDirectory)..\..\novolis-governance\build\Novolis.PackageReadme.props"
          Condition="Exists('$(MSBuildThisFileDirectory)..\..\novolis-governance\build\Novolis.PackageReadme.props')" />
</Project>
