// <auto-generated>
// Baseline holiday rules for Brazil. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Brazil (<c>BR</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class BrazilCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "BR";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Brazil, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Ano Novo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-16", "O"), Name: "Carnaval"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-17", "O"), Name: "Carnaval Terça-Feira Gorda"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-03", "O"), Name: "Sexta Feira Santa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-21", "O"), Name: "Dia de Tiradentes"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Dia do Trabalho"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-04", "O"), Name: "Corpus Christi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-09-07", "O"), Name: "Dia da Independência"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-12", "O"), Name: "Nossa Senhora Aparecida"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-02", "O"), Name: "Dia dos Finados"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-15", "O"), Name: "Dia da República"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Natal"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Ano Novo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-02-08", "O"), Name: "Carnaval"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-02-09", "O"), Name: "Carnaval Terça-Feira Gorda"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-26", "O"), Name: "Sexta Feira Santa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-04-21", "O"), Name: "Dia de Tiradentes"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Dia do Trabalho"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-27", "O"), Name: "Corpus Christi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-09-07", "O"), Name: "Dia da Independência"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-10-12", "O"), Name: "Nossa Senhora Aparecida"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-02", "O"), Name: "Dia dos Finados"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-15", "O"), Name: "Dia da República"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Natal"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Ano Novo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-28", "O"), Name: "Carnaval"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-29", "O"), Name: "Carnaval Terça-Feira Gorda"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Sexta Feira Santa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-21", "O"), Name: "Dia de Tiradentes"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Dia do Trabalho"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-15", "O"), Name: "Corpus Christi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-09-07", "O"), Name: "Dia da Independência"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-12", "O"), Name: "Nossa Senhora Aparecida"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-02", "O"), Name: "Dia dos Finados"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-15", "O"), Name: "Dia da República"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Natal"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Ano Novo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-12", "O"), Name: "Carnaval"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-13", "O"), Name: "Carnaval Terça-Feira Gorda"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-30", "O"), Name: "Sexta Feira Santa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-21", "O"), Name: "Dia de Tiradentes"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Dia do Trabalho"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-31", "O"), Name: "Corpus Christi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-09-07", "O"), Name: "Dia da Independência"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-12", "O"), Name: "Nossa Senhora Aparecida"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-02", "O"), Name: "Dia dos Finados"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-15", "O"), Name: "Dia da República"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Natal"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Ano Novo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-04", "O"), Name: "Carnaval"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-05", "O"), Name: "Carnaval Terça-Feira Gorda"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-19", "O"), Name: "Sexta Feira Santa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-21", "O"), Name: "Dia de Tiradentes"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Dia do Trabalho"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-20", "O"), Name: "Corpus Christi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-09-07", "O"), Name: "Dia da Independência"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-10-12", "O"), Name: "Nossa Senhora Aparecida"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-02", "O"), Name: "Dia dos Finados"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-15", "O"), Name: "Dia da República"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Natal"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Ano Novo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-24", "O"), Name: "Carnaval"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-25", "O"), Name: "Carnaval Terça-Feira Gorda"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Sexta Feira Santa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-21", "O"), Name: "Dia de Tiradentes"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Dia do Trabalho"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-12", "O"), Name: "Corpus Christi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-09-07", "O"), Name: "Dia da Independência"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-10-12", "O"), Name: "Nossa Senhora Aparecida"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-02", "O"), Name: "Dia dos Finados"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-15", "O"), Name: "Dia da República"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Natal")
        };
}
