// <auto-generated>
// Index of in-code calendar baselines. Regenerated by tools/GeneratePublicHolidays.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// In-code calendar baselines for the selected locations, 2026 through 2031.
/// Each collection is a default. Sparse configuration overrides individual dates.
/// </summary>
public static class CalendarCatalog
{
    /// <summary>First calendar year present in every baseline.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year present in every baseline.</summary>
    public const int LastYear = 2031;

    /// <summary>ISO country codes that have a generated baseline.</summary>
    public static IReadOnlyList<string> CountryCodes { get; } =
    [
        AustriaCalendar.CountryCode,
        AustraliaCalendar.CountryCode,
        BelgiumCalendar.CountryCode,
        BrazilCalendar.CountryCode,
        CanadaCalendar.CountryCode,
        SwitzerlandCalendar.CountryCode,
        CzechRepublicCalendar.CountryCode,
        GermanyCalendar.CountryCode,
        DenmarkCalendar.CountryCode,
        EstoniaCalendar.CountryCode,
        SpainCalendar.CountryCode,
        FinlandCalendar.CountryCode,
        FranceCalendar.CountryCode,
        UnitedKingdomCalendar.CountryCode,
        GreeceCalendar.CountryCode,
        CroatiaCalendar.CountryCode,
        HungaryCalendar.CountryCode,
        IrelandCalendar.CountryCode,
        ItalyCalendar.CountryCode,
        JapanCalendar.CountryCode,
        KazakhstanCalendar.CountryCode,
        LithuaniaCalendar.CountryCode,
        LuxembourgCalendar.CountryCode,
        MexicoCalendar.CountryCode,
        NetherlandsCalendar.CountryCode,
        NorwayCalendar.CountryCode,
        NewZealandCalendar.CountryCode,
        PolandCalendar.CountryCode,
        PortugalCalendar.CountryCode,
        RomaniaCalendar.CountryCode,
        SerbiaCalendar.CountryCode,
        SwedenCalendar.CountryCode,
        SloveniaCalendar.CountryCode,
        SlovakiaCalendar.CountryCode,
        TurkeyCalendar.CountryCode,
        UnitedStatesCalendar.CountryCode,
        SouthAfricaCalendar.CountryCode,
    ];

    /// <summary>Returns the baseline holiday rules for a selected location.</summary>
    public static IReadOnlyList<PublicHolidayFact> GetBaseline(string countryCode)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(countryCode);
        return countryCode.ToUpperInvariant() switch
        {
            AustriaCalendar.CountryCode => AustriaCalendar.Baseline,
            AustraliaCalendar.CountryCode => AustraliaCalendar.Baseline,
            BelgiumCalendar.CountryCode => BelgiumCalendar.Baseline,
            BrazilCalendar.CountryCode => BrazilCalendar.Baseline,
            CanadaCalendar.CountryCode => CanadaCalendar.Baseline,
            SwitzerlandCalendar.CountryCode => SwitzerlandCalendar.Baseline,
            CzechRepublicCalendar.CountryCode => CzechRepublicCalendar.Baseline,
            GermanyCalendar.CountryCode => GermanyCalendar.Baseline,
            DenmarkCalendar.CountryCode => DenmarkCalendar.Baseline,
            EstoniaCalendar.CountryCode => EstoniaCalendar.Baseline,
            SpainCalendar.CountryCode => SpainCalendar.Baseline,
            FinlandCalendar.CountryCode => FinlandCalendar.Baseline,
            FranceCalendar.CountryCode => FranceCalendar.Baseline,
            UnitedKingdomCalendar.CountryCode => UnitedKingdomCalendar.Baseline,
            GreeceCalendar.CountryCode => GreeceCalendar.Baseline,
            CroatiaCalendar.CountryCode => CroatiaCalendar.Baseline,
            HungaryCalendar.CountryCode => HungaryCalendar.Baseline,
            IrelandCalendar.CountryCode => IrelandCalendar.Baseline,
            ItalyCalendar.CountryCode => ItalyCalendar.Baseline,
            JapanCalendar.CountryCode => JapanCalendar.Baseline,
            KazakhstanCalendar.CountryCode => KazakhstanCalendar.Baseline,
            LithuaniaCalendar.CountryCode => LithuaniaCalendar.Baseline,
            LuxembourgCalendar.CountryCode => LuxembourgCalendar.Baseline,
            MexicoCalendar.CountryCode => MexicoCalendar.Baseline,
            NetherlandsCalendar.CountryCode => NetherlandsCalendar.Baseline,
            NorwayCalendar.CountryCode => NorwayCalendar.Baseline,
            NewZealandCalendar.CountryCode => NewZealandCalendar.Baseline,
            PolandCalendar.CountryCode => PolandCalendar.Baseline,
            PortugalCalendar.CountryCode => PortugalCalendar.Baseline,
            RomaniaCalendar.CountryCode => RomaniaCalendar.Baseline,
            SerbiaCalendar.CountryCode => SerbiaCalendar.Baseline,
            SwedenCalendar.CountryCode => SwedenCalendar.Baseline,
            SloveniaCalendar.CountryCode => SloveniaCalendar.Baseline,
            SlovakiaCalendar.CountryCode => SlovakiaCalendar.Baseline,
            TurkeyCalendar.CountryCode => TurkeyCalendar.Baseline,
            UnitedStatesCalendar.CountryCode => UnitedStatesCalendar.Baseline,
            SouthAfricaCalendar.CountryCode => SouthAfricaCalendar.Baseline,
            _ => throw new InvalidOperationException(
                $"No generated calendar baseline exists for {countryCode}. Regenerate with the private GeneratePublicHolidays tool."),
        };
    }
}
