// <auto-generated>
// Baseline holiday rules for Canada. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Canada (<c>CA</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class CanadaCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "CA";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Canada, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-03", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-18", "O"), Name: "Victoria Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-07-01", "O"), Name: "Canada Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-03", "O"), Name: "Civic Holiday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-09-07", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-09-30", "O"), Name: "National Day For Truth And Reconciliation"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-12", "O"), Name: "Thanksgiving Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-11", "O"), Name: "Remembrance Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Boxing Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-26", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-24", "O"), Name: "Victoria Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-07-01", "O"), Name: "Canada Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-02", "O"), Name: "Civic Holiday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-09-06", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-09-30", "O"), Name: "National Day For Truth And Reconciliation"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-10-11", "O"), Name: "Thanksgiving Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-11", "O"), Name: "Remembrance Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Boxing Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-27", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-03", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-22", "O"), Name: "Victoria Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-07-03", "O"), Name: "Canada Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-07", "O"), Name: "Civic Holiday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-09-04", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-02", "O"), Name: "National Day For Truth And Reconciliation"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-09", "O"), Name: "Thanksgiving Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-13", "O"), Name: "Remembrance Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Boxing Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-30", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-21", "O"), Name: "Victoria Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-07-02", "O"), Name: "Canada Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-06", "O"), Name: "Civic Holiday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-09-03", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-01", "O"), Name: "National Day For Truth And Reconciliation"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-08", "O"), Name: "Thanksgiving Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-12", "O"), Name: "Remembrance Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Boxing Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-19", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-20", "O"), Name: "Victoria Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-07-01", "O"), Name: "Canada Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-05", "O"), Name: "Civic Holiday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-09-02", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-09-30", "O"), Name: "National Day For Truth And Reconciliation"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-10-14", "O"), Name: "Thanksgiving Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-11", "O"), Name: "Remembrance Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Boxing Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-19", "O"), Name: "Victoria Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-07-01", "O"), Name: "Canada Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-04", "O"), Name: "Civic Holiday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-09-01", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-09-30", "O"), Name: "National Day For Truth And Reconciliation"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-10-13", "O"), Name: "Thanksgiving Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-11", "O"), Name: "Remembrance Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Boxing Day")
        };
}
