// <auto-generated>
// Baseline holiday rules for Croatia. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Croatia (<c>HR</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class CroatiaCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "HR";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Croatia, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Nova godina"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-06", "O"), Name: "Bogojavljenje ili Sveta tri kralja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Uskrsni ponedjeljak"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Praznik rada"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-30", "O"), Name: "Dan državnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-04", "O"), Name: "Tijelovo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-22", "O"), Name: "Dan antifašističke borbe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-05", "O"), Name: "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-15", "O"), Name: "Velika Gospa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-01", "O"), Name: "Svi sveti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-18", "O"), Name: "Dan sjećanja na žrtve Domovinskog rata i Dan sjećanja na žrtvu Vukovara i Škabrnje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Božić"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Sveti Stjepan"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Nova godina"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-06", "O"), Name: "Bogojavljenje ili Sveta tri kralja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Uskrsni ponedjeljak"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Praznik rada"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-27", "O"), Name: "Tijelovo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-30", "O"), Name: "Dan državnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-22", "O"), Name: "Dan antifašističke borbe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-05", "O"), Name: "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-15", "O"), Name: "Velika Gospa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-01", "O"), Name: "Svi sveti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-18", "O"), Name: "Dan sjećanja na žrtve Domovinskog rata i Dan sjećanja na žrtvu Vukovara i Škabrnje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Božić"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Sveti Stjepan"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Nova godina"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-06", "O"), Name: "Bogojavljenje ili Sveta tri kralja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Uskrsni ponedjeljak"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Praznik rada"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-30", "O"), Name: "Dan državnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-15", "O"), Name: "Tijelovo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-22", "O"), Name: "Dan antifašističke borbe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-05", "O"), Name: "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-15", "O"), Name: "Velika Gospa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-01", "O"), Name: "Svi sveti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-18", "O"), Name: "Dan sjećanja na žrtve Domovinskog rata i Dan sjećanja na žrtvu Vukovara i Škabrnje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Božić"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Sveti Stjepan"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Nova godina"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-06", "O"), Name: "Bogojavljenje ili Sveta tri kralja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Uskrsni ponedjeljak"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Praznik rada"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-30", "O"), Name: "Dan državnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-31", "O"), Name: "Tijelovo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-22", "O"), Name: "Dan antifašističke borbe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-05", "O"), Name: "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-15", "O"), Name: "Velika Gospa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-01", "O"), Name: "Svi sveti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-18", "O"), Name: "Dan sjećanja na žrtve Domovinskog rata i Dan sjećanja na žrtvu Vukovara i Škabrnje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Božić"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Sveti Stjepan"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Nova godina"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-06", "O"), Name: "Bogojavljenje ili Sveta tri kralja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Uskrsni ponedjeljak"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Praznik rada"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-30", "O"), Name: "Dan državnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-20", "O"), Name: "Tijelovo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-22", "O"), Name: "Dan antifašističke borbe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-05", "O"), Name: "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-15", "O"), Name: "Velika Gospa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-01", "O"), Name: "Svi sveti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-18", "O"), Name: "Dan sjećanja na žrtve Domovinskog rata i Dan sjećanja na žrtvu Vukovara i Škabrnje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Božić"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Sveti Stjepan"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Nova godina"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-06", "O"), Name: "Bogojavljenje ili Sveta tri kralja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Uskrsni ponedjeljak"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Praznik rada"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-30", "O"), Name: "Dan državnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-12", "O"), Name: "Tijelovo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-22", "O"), Name: "Dan antifašističke borbe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-05", "O"), Name: "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-15", "O"), Name: "Velika Gospa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-01", "O"), Name: "Svi sveti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-18", "O"), Name: "Dan sjećanja na žrtve Domovinskog rata i Dan sjećanja na žrtvu Vukovara i Škabrnje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Božić"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Sveti Stjepan")
        };
}
