// <auto-generated>
// Baseline holiday rules for Czech Republic. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Czech Republic (<c>CZ</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class CzechRepublicCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "CZ";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Czech Republic, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Den obnovy samostatného českého státu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-03", "O"), Name: "Velký Pátek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Pondělí Velikonoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Svátek práce"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-08", "O"), Name: "Den osvobození"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-07-05", "O"), Name: "Den slovanských věrozvěstů Cyrila a Metoděje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-07-06", "O"), Name: "Den upálení mistra Jana Husa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-09-28", "O"), Name: "Den české státnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-28", "O"), Name: "Den vzniku samostatného československého státu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-17", "O"), Name: "Den boje za svobodu a demokracii"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-24", "O"), Name: "Štědrý den"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "První svátek vánoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Druhý svátek vánoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Den obnovy samostatného českého státu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-26", "O"), Name: "Velký Pátek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Pondělí Velikonoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Svátek práce"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-08", "O"), Name: "Den osvobození"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-07-05", "O"), Name: "Den slovanských věrozvěstů Cyrila a Metoděje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-07-06", "O"), Name: "Den upálení mistra Jana Husa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-09-28", "O"), Name: "Den české státnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-10-28", "O"), Name: "Den vzniku samostatného československého státu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-17", "O"), Name: "Den boje za svobodu a demokracii"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-24", "O"), Name: "Štědrý den"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "První svátek vánoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Druhý svátek vánoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Den obnovy samostatného českého státu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Velký Pátek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Pondělí Velikonoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Svátek práce"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-08", "O"), Name: "Den osvobození"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-07-05", "O"), Name: "Den slovanských věrozvěstů Cyrila a Metoděje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-07-06", "O"), Name: "Den upálení mistra Jana Husa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-09-28", "O"), Name: "Den české státnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-28", "O"), Name: "Den vzniku samostatného československého státu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-17", "O"), Name: "Den boje za svobodu a demokracii"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-24", "O"), Name: "Štědrý den"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "První svátek vánoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Druhý svátek vánoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Den obnovy samostatného českého státu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-30", "O"), Name: "Velký Pátek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Pondělí Velikonoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Svátek práce"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-08", "O"), Name: "Den osvobození"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-07-05", "O"), Name: "Den slovanských věrozvěstů Cyrila a Metoděje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-07-06", "O"), Name: "Den upálení mistra Jana Husa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-09-28", "O"), Name: "Den české státnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-28", "O"), Name: "Den vzniku samostatného československého státu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-17", "O"), Name: "Den boje za svobodu a demokracii"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-24", "O"), Name: "Štědrý den"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "První svátek vánoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Druhý svátek vánoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Den obnovy samostatného českého státu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-19", "O"), Name: "Velký Pátek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Pondělí Velikonoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Svátek práce"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-08", "O"), Name: "Den osvobození"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-07-05", "O"), Name: "Den slovanských věrozvěstů Cyrila a Metoděje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-07-06", "O"), Name: "Den upálení mistra Jana Husa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-09-28", "O"), Name: "Den české státnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-10-28", "O"), Name: "Den vzniku samostatného československého státu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-17", "O"), Name: "Den boje za svobodu a demokracii"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-24", "O"), Name: "Štědrý den"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "První svátek vánoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Druhý svátek vánoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Den obnovy samostatného českého státu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Velký Pátek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Pondělí Velikonoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Svátek práce"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-08", "O"), Name: "Den osvobození"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-07-05", "O"), Name: "Den slovanských věrozvěstů Cyrila a Metoděje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-07-06", "O"), Name: "Den upálení mistra Jana Husa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-09-28", "O"), Name: "Den české státnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-10-28", "O"), Name: "Den vzniku samostatného československého státu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-17", "O"), Name: "Den boje za svobodu a demokracii"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-24", "O"), Name: "Štědrý den"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "První svátek vánoční"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Druhý svátek vánoční")
        };
}
