// <auto-generated>
// Baseline holiday rules for Denmark. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Denmark (<c>DK</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class DenmarkCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "DK";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Denmark, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Nytårsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-02", "O"), Name: "Skærtorsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-03", "O"), Name: "Langfredag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-05", "O"), Name: "Påskedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Anden påskedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Første maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-14", "O"), Name: "Kristi himmelfartsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-24", "O"), Name: "Pinsedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-25", "O"), Name: "Anden pinsedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-05", "O"), Name: "Grundlovsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Første juledag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Anden juledag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Nytårsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-25", "O"), Name: "Skærtorsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-26", "O"), Name: "Langfredag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-28", "O"), Name: "Påskedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Anden påskedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Første maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-06", "O"), Name: "Kristi himmelfartsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-16", "O"), Name: "Pinsedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-17", "O"), Name: "Anden pinsedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-05", "O"), Name: "Grundlovsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Første juledag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Anden juledag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Nytårsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-13", "O"), Name: "Skærtorsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Langfredag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-16", "O"), Name: "Påskedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Anden påskedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Første maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-25", "O"), Name: "Kristi himmelfartsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-04", "O"), Name: "Pinsedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-05", "O"), Name: "Grundlovsdag, Anden pinsedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Første juledag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Anden juledag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Nytårsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-29", "O"), Name: "Skærtorsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-30", "O"), Name: "Langfredag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-01", "O"), Name: "Påskedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Anden påskedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Første maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-10", "O"), Name: "Kristi himmelfartsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-20", "O"), Name: "Pinsedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-21", "O"), Name: "Anden pinsedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-05", "O"), Name: "Grundlovsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Første juledag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Anden juledag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Nytårsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-18", "O"), Name: "Skærtorsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-19", "O"), Name: "Langfredag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-21", "O"), Name: "Påskedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Anden påskedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Første maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-30", "O"), Name: "Kristi himmelfartsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-05", "O"), Name: "Grundlovsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-09", "O"), Name: "Pinsedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-10", "O"), Name: "Anden pinsedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Første juledag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Anden juledag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Nytårsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-10", "O"), Name: "Skærtorsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Langfredag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-13", "O"), Name: "Påskedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Anden påskedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Første maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-22", "O"), Name: "Kristi himmelfartsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-01", "O"), Name: "Pinsedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-02", "O"), Name: "Anden pinsedag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-05", "O"), Name: "Grundlovsdag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Første juledag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Anden juledag")
        };
}
