// <auto-generated>
// Baseline holiday rules for Estonia. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Estonia (<c>EE</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class EstoniaCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "EE";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Estonia, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Uusaasta"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-24", "O"), Name: "Iseseisvumispäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-03", "O"), Name: "Suur reede"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-05", "O"), Name: "Ülestõusmispühade 1. püha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Kevadpüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-24", "O"), Name: "Nelipühade 1. püha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-23", "O"), Name: "Võidupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-24", "O"), Name: "Jaanipäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-20", "O"), Name: "Taasiseseisvumispäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-24", "O"), Name: "Jõululaupäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Esimene jõulupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Teine jõulupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Uusaasta"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-02-24", "O"), Name: "Iseseisvumispäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-26", "O"), Name: "Suur reede"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-28", "O"), Name: "Ülestõusmispühade 1. püha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Kevadpüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-16", "O"), Name: "Nelipühade 1. püha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-23", "O"), Name: "Võidupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-24", "O"), Name: "Jaanipäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-20", "O"), Name: "Taasiseseisvumispäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-24", "O"), Name: "Jõululaupäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Esimene jõulupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Teine jõulupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Uusaasta"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-24", "O"), Name: "Iseseisvumispäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Suur reede"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-16", "O"), Name: "Ülestõusmispühade 1. püha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Kevadpüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-04", "O"), Name: "Nelipühade 1. püha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-23", "O"), Name: "Võidupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-24", "O"), Name: "Jaanipäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-20", "O"), Name: "Taasiseseisvumispäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-24", "O"), Name: "Jõululaupäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Esimene jõulupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Teine jõulupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Uusaasta"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-24", "O"), Name: "Iseseisvumispäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-30", "O"), Name: "Suur reede"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-01", "O"), Name: "Ülestõusmispühade 1. püha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Kevadpüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-20", "O"), Name: "Nelipühade 1. püha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-23", "O"), Name: "Võidupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-24", "O"), Name: "Jaanipäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-20", "O"), Name: "Taasiseseisvumispäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-24", "O"), Name: "Jõululaupäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Esimene jõulupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Teine jõulupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Uusaasta"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-02-24", "O"), Name: "Iseseisvumispäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-19", "O"), Name: "Suur reede"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-21", "O"), Name: "Ülestõusmispühade 1. püha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Kevadpüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-09", "O"), Name: "Nelipühade 1. püha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-23", "O"), Name: "Võidupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-24", "O"), Name: "Jaanipäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-20", "O"), Name: "Taasiseseisvumispäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-24", "O"), Name: "Jõululaupäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Esimene jõulupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Teine jõulupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Uusaasta"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-24", "O"), Name: "Iseseisvumispäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Suur reede"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-13", "O"), Name: "Ülestõusmispühade 1. püha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Kevadpüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-01", "O"), Name: "Nelipühade 1. püha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-23", "O"), Name: "Võidupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-24", "O"), Name: "Jaanipäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-20", "O"), Name: "Taasiseseisvumispäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-24", "O"), Name: "Jõululaupäev"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Esimene jõulupüha"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Teine jõulupüha")
        };
}
