// <auto-generated>
// Baseline holiday rules for Finland. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Finland (<c>FI</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class FinlandCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "FI";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Finland, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Uudenvuodenpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-06", "O"), Name: "Loppiainen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-03", "O"), Name: "Pitkäperjantai"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-05", "O"), Name: "Pääsiäispäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "2. pääsiäispäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Vappu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-14", "O"), Name: "Helatorstai"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-24", "O"), Name: "Helluntaipäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-20", "O"), Name: "Juhannuspäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-31", "O"), Name: "Pyhäinpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-06", "O"), Name: "Itsenäisyyspäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Joulupäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Tapaninpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Uudenvuodenpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-06", "O"), Name: "Loppiainen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-26", "O"), Name: "Pitkäperjantai"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-28", "O"), Name: "Pääsiäispäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "2. pääsiäispäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Vappu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-06", "O"), Name: "Helatorstai"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-16", "O"), Name: "Helluntaipäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-26", "O"), Name: "Juhannuspäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-06", "O"), Name: "Pyhäinpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-06", "O"), Name: "Itsenäisyyspäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Joulupäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Tapaninpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Uudenvuodenpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-06", "O"), Name: "Loppiainen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Pitkäperjantai"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-16", "O"), Name: "Pääsiäispäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "2. pääsiäispäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Vappu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-25", "O"), Name: "Helatorstai"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-04", "O"), Name: "Helluntaipäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-24", "O"), Name: "Juhannuspäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-04", "O"), Name: "Pyhäinpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-06", "O"), Name: "Itsenäisyyspäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Joulupäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Tapaninpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Uudenvuodenpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-06", "O"), Name: "Loppiainen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-30", "O"), Name: "Pitkäperjantai"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-01", "O"), Name: "Pääsiäispäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "2. pääsiäispäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Vappu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-10", "O"), Name: "Helatorstai"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-20", "O"), Name: "Helluntaipäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-23", "O"), Name: "Juhannuspäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-03", "O"), Name: "Pyhäinpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-06", "O"), Name: "Itsenäisyyspäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Joulupäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Tapaninpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Uudenvuodenpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-06", "O"), Name: "Loppiainen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-19", "O"), Name: "Pitkäperjantai"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-21", "O"), Name: "Pääsiäispäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "2. pääsiäispäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Vappu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-30", "O"), Name: "Helatorstai"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-09", "O"), Name: "Helluntaipäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-22", "O"), Name: "Juhannuspäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-02", "O"), Name: "Pyhäinpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-06", "O"), Name: "Itsenäisyyspäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Joulupäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Tapaninpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Uudenvuodenpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-06", "O"), Name: "Loppiainen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Pitkäperjantai"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-13", "O"), Name: "Pääsiäispäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "2. pääsiäispäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Vappu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-22", "O"), Name: "Helatorstai"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-01", "O"), Name: "Helluntaipäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-21", "O"), Name: "Juhannuspäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-01", "O"), Name: "Pyhäinpäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-06", "O"), Name: "Itsenäisyyspäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Joulupäivä"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Tapaninpäivä")
        };
}
