// <auto-generated>
// Baseline holiday rules for France. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for France (<c>FR</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class FranceCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "FR";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for France, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Nouvel An"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Lundi de Pâques"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Fête du Travail"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-08", "O"), Name: "Fête de la Victoire"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-14", "O"), Name: "Jeudi de l\'Ascension"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-25", "O"), Name: "Lundi de Pentecôte"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-07-14", "O"), Name: "Fête nationale"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-15", "O"), Name: "Assomption"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-01", "O"), Name: "Toussaint"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-11", "O"), Name: "Jour de l\'armistice"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Noël"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Nouvel An"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Lundi de Pâques"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Fête du Travail"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-06", "O"), Name: "Jeudi de l\'Ascension"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-08", "O"), Name: "Fête de la Victoire"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-17", "O"), Name: "Lundi de Pentecôte"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-07-14", "O"), Name: "Fête nationale"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-15", "O"), Name: "Assomption"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-01", "O"), Name: "Toussaint"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-11", "O"), Name: "Jour de l\'armistice"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Noël"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Nouvel An"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Lundi de Pâques"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Fête du Travail"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-08", "O"), Name: "Fête de la Victoire"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-25", "O"), Name: "Jeudi de l\'Ascension"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-05", "O"), Name: "Lundi de Pentecôte"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-07-14", "O"), Name: "Fête nationale"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-15", "O"), Name: "Assomption"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-01", "O"), Name: "Toussaint"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-11", "O"), Name: "Jour de l\'armistice"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Noël"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Nouvel An"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Lundi de Pâques"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Fête du Travail"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-08", "O"), Name: "Fête de la Victoire"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-10", "O"), Name: "Jeudi de l\'Ascension"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-21", "O"), Name: "Lundi de Pentecôte"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-07-14", "O"), Name: "Fête nationale"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-15", "O"), Name: "Assomption"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-01", "O"), Name: "Toussaint"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-11", "O"), Name: "Jour de l\'armistice"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Noël"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Nouvel An"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Lundi de Pâques"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Fête du Travail"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-08", "O"), Name: "Fête de la Victoire"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-30", "O"), Name: "Jeudi de l\'Ascension"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-10", "O"), Name: "Lundi de Pentecôte"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-07-14", "O"), Name: "Fête nationale"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-15", "O"), Name: "Assomption"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-01", "O"), Name: "Toussaint"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-11", "O"), Name: "Jour de l\'armistice"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Noël"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Nouvel An"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Lundi de Pâques"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Fête du Travail"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-08", "O"), Name: "Fête de la Victoire"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-22", "O"), Name: "Jeudi de l\'Ascension"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-02", "O"), Name: "Lundi de Pentecôte"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-07-14", "O"), Name: "Fête nationale"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-15", "O"), Name: "Assomption"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-01", "O"), Name: "Toussaint"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-11", "O"), Name: "Jour de l\'armistice"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Noël")
        };
}
