// <auto-generated>
// Source identity recorded with the in-code calendar baselines.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Source identity for the generated calendar baselines covering 2026 through 2031.
/// </summary>
public static class GeneratedCalendarSource
{
    /// <summary>Package that supplied the holiday rules.</summary>
    public const string Package = "PublicHoliday";

    /// <summary>Package version recorded at generation.</summary>
    public const string PackageVersion = "3.16.0.0";

    /// <summary>Generator revision that wrote the baselines.</summary>
    public const string GeneratorVersion = "novolis-time-holiday-generator-2";
}
