// <auto-generated>
// Baseline holiday rules for Greece. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Greece (<c>GR</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class GreeceCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "GR";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Greece, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "New Year\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-06", "O"), Name: "Epiphany"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-23", "O"), Name: "Clean Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-03-25", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-10", "O"), Name: "Great Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-13", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-01", "O"), Name: "Whit Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-15", "O"), Name: "Dormition of the Mother of God"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-28", "O"), Name: "Ochi Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Glorifying Mother of God"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "New Year\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-06", "O"), Name: "Epiphany"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-15", "O"), Name: "Clean Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-25", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-04-30", "O"), Name: "Great Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-03", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-21", "O"), Name: "Whit Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-15", "O"), Name: "Dormition of the Mother of God"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-10-28", "O"), Name: "Ochi Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Glorifying Mother of God"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "New Year\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-06", "O"), Name: "Epiphany"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-28", "O"), Name: "Clean Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-03-25", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Great Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-05", "O"), Name: "Whit Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-15", "O"), Name: "Dormition of the Mother of God"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-28", "O"), Name: "Ochi Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Glorifying Mother of God"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "New Year\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-06", "O"), Name: "Epiphany"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-19", "O"), Name: "Clean Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-25", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-06", "O"), Name: "Great Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-09", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-28", "O"), Name: "Whit Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-15", "O"), Name: "Dormition of the Mother of God"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-28", "O"), Name: "Ochi Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Glorifying Mother of God"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "New Year\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-06", "O"), Name: "Epiphany"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-11", "O"), Name: "Clean Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-25", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-26", "O"), Name: "Great Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-29", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-17", "O"), Name: "Whit Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-15", "O"), Name: "Dormition of the Mother of God"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-10-28", "O"), Name: "Ochi Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Glorifying Mother of God"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "New Year\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-06", "O"), Name: "Epiphany"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-24", "O"), Name: "Clean Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-03-25", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Great Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-02", "O"), Name: "Whit Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-15", "O"), Name: "Dormition of the Mother of God"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-10-28", "O"), Name: "Ochi Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Glorifying Mother of God")
        };
}
