// <auto-generated>
// Baseline holiday rules for Hungary. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Hungary (<c>HU</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class HungaryCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "HU";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Hungary, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Újév"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-03-15", "O"), Name: "1848-as forradalom ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-03", "O"), Name: "Nagypéntek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Húsvéthétfő"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Munka ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-25", "O"), Name: "Pünkösdhétfő"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-20", "O"), Name: "Államalapítás ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-23", "O"), Name: "1956-os forradalom ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-01", "O"), Name: "Mindenszentek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Karácsony"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Karácsony másnapja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Újév"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-15", "O"), Name: "1848-as forradalom ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-26", "O"), Name: "Nagypéntek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Húsvéthétfő"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Munka ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-17", "O"), Name: "Pünkösdhétfő"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-20", "O"), Name: "Államalapítás ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-10-23", "O"), Name: "1956-os forradalom ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-01", "O"), Name: "Mindenszentek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Karácsony"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Karácsony másnapja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Újév"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-03-15", "O"), Name: "1848-as forradalom ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Nagypéntek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Húsvéthétfő"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Munka ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-05", "O"), Name: "Pünkösdhétfő"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-20", "O"), Name: "Államalapítás ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-23", "O"), Name: "1956-os forradalom ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-01", "O"), Name: "Mindenszentek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Karácsony"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Karácsony másnapja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Újév"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-15", "O"), Name: "1848-as forradalom ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-30", "O"), Name: "Nagypéntek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Húsvéthétfő"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Munka ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-21", "O"), Name: "Pünkösdhétfő"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-20", "O"), Name: "Államalapítás ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-23", "O"), Name: "1956-os forradalom ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-01", "O"), Name: "Mindenszentek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Karácsony"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Karácsony másnapja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Újév"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-15", "O"), Name: "1848-as forradalom ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-19", "O"), Name: "Nagypéntek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Húsvéthétfő"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Munka ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-10", "O"), Name: "Pünkösdhétfő"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-20", "O"), Name: "Államalapítás ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-10-23", "O"), Name: "1956-os forradalom ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-01", "O"), Name: "Mindenszentek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Karácsony"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Karácsony másnapja"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Újév"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-03-15", "O"), Name: "1848-as forradalom ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Nagypéntek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Húsvéthétfő"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Munka ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-02", "O"), Name: "Pünkösdhétfő"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-20", "O"), Name: "Államalapítás ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-10-23", "O"), Name: "1956-os forradalom ünnepe"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-01", "O"), Name: "Mindenszentek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Karácsony"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Karácsony másnapja")
        };
}
