// <auto-generated>
// Baseline holiday rules for Ireland. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Ireland (<c>IE</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class IrelandCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "IE";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Ireland, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Lá Caille"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-02", "O"), Name: "Imbolc"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-03-17", "O"), Name: "Lá Fhéile Pádraig"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Luan Cásca"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-04", "O"), Name: "Lá Bealtaine"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-01", "O"), Name: "Lá Saoire i mí an Mheithimh"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-03", "O"), Name: "Lá Saoire i mí Lúnasa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-26", "O"), Name: "Lá Saoire i mí Dheireadh Fómhair"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Lá Nollag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Lá Fhéile Stiofáin"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Lá Caille"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-02-01", "O"), Name: "Imbolc"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-17", "O"), Name: "Lá Fhéile Pádraig"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Luan Cásca"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-03", "O"), Name: "Lá Bealtaine"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-07", "O"), Name: "Lá Saoire i mí an Mheithimh"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-02", "O"), Name: "Lá Saoire i mí Lúnasa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-10-25", "O"), Name: "Lá Saoire i mí Dheireadh Fómhair"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Lá Nollag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Lá Fhéile Stiofáin"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Lá Caille"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-07", "O"), Name: "Imbolc"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-03-17", "O"), Name: "Lá Fhéile Pádraig"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Luan Cásca"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Lá Bealtaine"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-05", "O"), Name: "Lá Saoire i mí an Mheithimh"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-07", "O"), Name: "Lá Saoire i mí Lúnasa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-30", "O"), Name: "Lá Saoire i mí Dheireadh Fómhair"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Lá Nollag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Lá Fhéile Stiofáin"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Lá Caille"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-05", "O"), Name: "Imbolc"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-17", "O"), Name: "Lá Fhéile Pádraig"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Luan Cásca"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-07", "O"), Name: "Lá Bealtaine"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-04", "O"), Name: "Lá Saoire i mí an Mheithimh"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-06", "O"), Name: "Lá Saoire i mí Lúnasa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-29", "O"), Name: "Lá Saoire i mí Dheireadh Fómhair"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Lá Nollag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Lá Fhéile Stiofáin"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Lá Caille"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-02-01", "O"), Name: "Imbolc"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-17", "O"), Name: "Lá Fhéile Pádraig"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Luan Cásca"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-06", "O"), Name: "Lá Bealtaine"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-03", "O"), Name: "Lá Saoire i mí an Mheithimh"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-05", "O"), Name: "Lá Saoire i mí Lúnasa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-10-28", "O"), Name: "Lá Saoire i mí Dheireadh Fómhair"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Lá Nollag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Lá Fhéile Stiofáin"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Lá Caille"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-03", "O"), Name: "Imbolc"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-03-17", "O"), Name: "Lá Fhéile Pádraig"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Luan Cásca"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-05", "O"), Name: "Lá Bealtaine"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-02", "O"), Name: "Lá Saoire i mí an Mheithimh"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-04", "O"), Name: "Lá Saoire i mí Lúnasa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-10-27", "O"), Name: "Lá Saoire i mí Dheireadh Fómhair"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Lá Nollag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Lá Fhéile Stiofáin")
        };
}
