// <auto-generated>
// Baseline holiday rules for Italy. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Italy (<c>IT</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class ItalyCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "IT";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Italy, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Capodanno"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-06", "O"), Name: "Epifania"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-05", "O"), Name: "Pasqua"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Pasquetta"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-25", "O"), Name: "Festa della Liberazione"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Festa del Lavoro"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-02", "O"), Name: "Festa della Repubblica"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-15", "O"), Name: "Ferragosto"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-01", "O"), Name: "Tutti i santi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-08", "O"), Name: "Immacolata Concezione"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Natale"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Santo Stefano"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Capodanno"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-06", "O"), Name: "Epifania"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-28", "O"), Name: "Pasqua"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Pasquetta"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-04-25", "O"), Name: "Festa della Liberazione"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Festa del Lavoro"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-02", "O"), Name: "Festa della Repubblica"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-15", "O"), Name: "Ferragosto"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-01", "O"), Name: "Tutti i santi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-08", "O"), Name: "Immacolata Concezione"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Natale"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Santo Stefano"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Capodanno"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-06", "O"), Name: "Epifania"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-16", "O"), Name: "Pasqua"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Pasquetta"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-25", "O"), Name: "Festa della Liberazione"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Festa del Lavoro"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-02", "O"), Name: "Festa della Repubblica"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-15", "O"), Name: "Ferragosto"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-01", "O"), Name: "Tutti i santi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-08", "O"), Name: "Immacolata Concezione"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Natale"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Santo Stefano"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Capodanno"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-06", "O"), Name: "Epifania"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-01", "O"), Name: "Pasqua"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Pasquetta"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-25", "O"), Name: "Festa della Liberazione"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Festa del Lavoro"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-02", "O"), Name: "Festa della Repubblica"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-15", "O"), Name: "Ferragosto"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-01", "O"), Name: "Tutti i santi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-08", "O"), Name: "Immacolata Concezione"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Natale"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Santo Stefano"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Capodanno"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-06", "O"), Name: "Epifania"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-21", "O"), Name: "Pasqua"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Pasquetta"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-25", "O"), Name: "Festa della Liberazione"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Festa del Lavoro"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-02", "O"), Name: "Festa della Repubblica"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-15", "O"), Name: "Ferragosto"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-01", "O"), Name: "Tutti i santi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-08", "O"), Name: "Immacolata Concezione"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Natale"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Santo Stefano"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Capodanno"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-06", "O"), Name: "Epifania"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-13", "O"), Name: "Pasqua"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Pasquetta"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-25", "O"), Name: "Festa della Liberazione"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Festa del Lavoro"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-02", "O"), Name: "Festa della Repubblica"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-15", "O"), Name: "Ferragosto"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-01", "O"), Name: "Tutti i santi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-08", "O"), Name: "Immacolata Concezione"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Natale"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Santo Stefano")
        };
}
