// <auto-generated>
// Baseline holiday rules for Japan. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Japan (<c>JP</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class JapanCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "JP";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Japan, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-12", "O"), Name: "Coming Of Age Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-11", "O"), Name: "Foundation Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-23", "O"), Name: "Emperor\'s Birthday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-03-20", "O"), Name: "Vernal Equinox Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-29", "O"), Name: "Shōwa Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-04", "O"), Name: "Greenery Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-05", "O"), Name: "Children\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-06", "O"), Name: "Constitution Memorial Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-07-20", "O"), Name: "Marine Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-11", "O"), Name: "Mountain Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-09-21", "O"), Name: "Respect For The Aged Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-09-23", "O"), Name: "Autumnal Equinox Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-12", "O"), Name: "Health And Sports Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-03", "O"), Name: "Culture Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-23", "O"), Name: "Labour Thanksgiving Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-11", "O"), Name: "Coming Of Age Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-02-11", "O"), Name: "Foundation Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-02-23", "O"), Name: "Emperor\'s Birthday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-22", "O"), Name: "Vernal Equinox Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-04-29", "O"), Name: "Shōwa Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-03", "O"), Name: "Constitution Memorial Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-04", "O"), Name: "Greenery Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-05", "O"), Name: "Children\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-07-19", "O"), Name: "Marine Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-11", "O"), Name: "Mountain Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-09-20", "O"), Name: "Respect For The Aged Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-09-23", "O"), Name: "Autumnal Equinox Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-10-11", "O"), Name: "Health And Sports Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-03", "O"), Name: "Culture Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-23", "O"), Name: "Labour Thanksgiving Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-10", "O"), Name: "Coming Of Age Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-11", "O"), Name: "Foundation Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-23", "O"), Name: "Emperor\'s Birthday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-03-20", "O"), Name: "Vernal Equinox Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-29", "O"), Name: "Shōwa Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-03", "O"), Name: "Constitution Memorial Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-04", "O"), Name: "Greenery Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-05", "O"), Name: "Children\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-07-17", "O"), Name: "Marine Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-11", "O"), Name: "Mountain Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-09-18", "O"), Name: "Respect For The Aged Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-09-22", "O"), Name: "Autumnal Equinox Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-09", "O"), Name: "Health And Sports Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-03", "O"), Name: "Culture Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-23", "O"), Name: "Labour Thanksgiving Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-08", "O"), Name: "Coming Of Age Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-12", "O"), Name: "Foundation Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-23", "O"), Name: "Emperor\'s Birthday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-20", "O"), Name: "Vernal Equinox Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-30", "O"), Name: "Shōwa Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-03", "O"), Name: "Constitution Memorial Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-04", "O"), Name: "Greenery Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-05", "O"), Name: "Children\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-07-16", "O"), Name: "Marine Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-11", "O"), Name: "Mountain Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-09-17", "O"), Name: "Respect For The Aged Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-09-24", "O"), Name: "Autumnal Equinox Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-08", "O"), Name: "Health And Sports Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-03", "O"), Name: "Culture Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-23", "O"), Name: "Labour Thanksgiving Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-14", "O"), Name: "Coming Of Age Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-02-11", "O"), Name: "Foundation Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-02-23", "O"), Name: "Emperor\'s Birthday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-20", "O"), Name: "Vernal Equinox Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-29", "O"), Name: "Shōwa Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-03", "O"), Name: "Constitution Memorial Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-04", "O"), Name: "Greenery Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-06", "O"), Name: "Children\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-07-15", "O"), Name: "Marine Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-12", "O"), Name: "Mountain Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-09-16", "O"), Name: "Respect For The Aged Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-09-23", "O"), Name: "Autumnal Equinox Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-10-14", "O"), Name: "Health And Sports Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-04", "O"), Name: "Culture Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-23", "O"), Name: "Labour Thanksgiving Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-13", "O"), Name: "Coming Of Age Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-11", "O"), Name: "Foundation Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-24", "O"), Name: "Emperor\'s Birthday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-03-21", "O"), Name: "Vernal Equinox Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-29", "O"), Name: "Shōwa Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-03", "O"), Name: "Constitution Memorial Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-05", "O"), Name: "Children\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-06", "O"), Name: "Greenery Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-07-21", "O"), Name: "Marine Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-11", "O"), Name: "Mountain Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-09-15", "O"), Name: "Respect For The Aged Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-09-23", "O"), Name: "Autumnal Equinox Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-10-13", "O"), Name: "Health And Sports Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-03", "O"), Name: "Culture Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-24", "O"), Name: "Labour Thanksgiving Day")
        };
}
