// <auto-generated>
// Baseline holiday rules for Kazakhstan. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Kazakhstan (<c>KZ</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class KazakhstanCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "KZ";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Kazakhstan, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Новый год"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-02", "O"), Name: "Второй день нового года"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-07", "O"), Name: "Рождество Христово"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-03-08", "O"), Name: "Международный женский день"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-03-21", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-03-22", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-03-23", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Праздник единства народа Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-07", "O"), Name: "День Защитника Отечества"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-09", "O"), Name: "День Победы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-07-06", "O"), Name: "День столицы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-30", "O"), Name: "День Конституции"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-09-01", "O"), Name: "Курбан Айт"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-01", "O"), Name: "День Первого Президента"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-16", "O"), Name: "День Независимости Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-17", "O"), Name: "День Независимости Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Новый год"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-02", "O"), Name: "Второй день нового года"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-07", "O"), Name: "Рождество Христово"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-08", "O"), Name: "Международный женский день"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-21", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-22", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-23", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Праздник единства народа Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-07", "O"), Name: "День Защитника Отечества"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-09", "O"), Name: "День Победы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-07-06", "O"), Name: "День столицы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-30", "O"), Name: "День Конституции"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-09-01", "O"), Name: "Курбан Айт"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-01", "O"), Name: "День Первого Президента"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-16", "O"), Name: "День Независимости Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-17", "O"), Name: "День Независимости Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Новый год"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-02", "O"), Name: "Второй день нового года"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-07", "O"), Name: "Рождество Христово"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-03-08", "O"), Name: "Международный женский день"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-03-21", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-03-22", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-03-23", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Праздник единства народа Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-07", "O"), Name: "День Защитника Отечества"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-09", "O"), Name: "День Победы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-07-06", "O"), Name: "День столицы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-30", "O"), Name: "День Конституции"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-09-01", "O"), Name: "Курбан Айт"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-01", "O"), Name: "День Первого Президента"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-16", "O"), Name: "День Независимости Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-17", "O"), Name: "День Независимости Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Новый год"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-02", "O"), Name: "Второй день нового года"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-07", "O"), Name: "Рождество Христово"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-08", "O"), Name: "Международный женский день"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-21", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-22", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-23", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Праздник единства народа Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-07", "O"), Name: "День Защитника Отечества"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-09", "O"), Name: "День Победы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-07-06", "O"), Name: "День столицы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-30", "O"), Name: "День Конституции"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-09-01", "O"), Name: "Курбан Айт"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-01", "O"), Name: "День Первого Президента"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-16", "O"), Name: "День Независимости Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-17", "O"), Name: "День Независимости Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Новый год"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-02", "O"), Name: "Второй день нового года"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-07", "O"), Name: "Рождество Христово"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-08", "O"), Name: "Международный женский день"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-21", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-22", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-23", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Праздник единства народа Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-07", "O"), Name: "День Защитника Отечества"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-09", "O"), Name: "День Победы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-07-06", "O"), Name: "День столицы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-30", "O"), Name: "День Конституции"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-09-01", "O"), Name: "Курбан Айт"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-01", "O"), Name: "День Первого Президента"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-16", "O"), Name: "День Независимости Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-17", "O"), Name: "День Независимости Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Новый год"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-02", "O"), Name: "Второй день нового года"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-07", "O"), Name: "Рождество Христово"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-03-08", "O"), Name: "Международный женский день"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-03-21", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-03-22", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-03-23", "O"), Name: "Наурыз мейрамы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Праздник единства народа Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-07", "O"), Name: "День Защитника Отечества"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-09", "O"), Name: "День Победы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-07-06", "O"), Name: "День столицы"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-30", "O"), Name: "День Конституции"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-09-01", "O"), Name: "Курбан Айт"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-01", "O"), Name: "День Первого Президента"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-16", "O"), Name: "День Независимости Казахстана"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-17", "O"), Name: "День Независимости Казахстана")
        };
}
