// <auto-generated>
// Baseline holiday rules for Lithuania. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Lithuania (<c>LT</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class LithuaniaCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "LT";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Lithuania, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Naujųjų metų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-16", "O"), Name: "Lietuvos valstybės atkūrimo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-03-11", "O"), Name: "Lietuvos nepriklausomybės atkūrimo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-05", "O"), Name: "Šv. Velykos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Antroji šv. Velykų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Tarptautinė darbo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-03", "O"), Name: "Motinos diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-07", "O"), Name: "Tėvo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-24", "O"), Name: "Rasos ir Joninių diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-07-06", "O"), Name: "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) ir Tautiškos giesmės diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-15", "O"), Name: "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-01", "O"), Name: "Visų šventųjų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-02", "O"), Name: "Mirusiųjų atminimo (Vėlinių) diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-24", "O"), Name: "Šv. Kūčios"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Šv. Kalėdos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Šv. Kalėdos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Naujųjų metų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-02-16", "O"), Name: "Lietuvos valstybės atkūrimo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-11", "O"), Name: "Lietuvos nepriklausomybės atkūrimo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-28", "O"), Name: "Šv. Velykos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Antroji šv. Velykų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Tarptautinė darbo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-02", "O"), Name: "Motinos diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-06", "O"), Name: "Tėvo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-24", "O"), Name: "Rasos ir Joninių diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-07-06", "O"), Name: "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) ir Tautiškos giesmės diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-15", "O"), Name: "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-01", "O"), Name: "Visų šventųjų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-02", "O"), Name: "Mirusiųjų atminimo (Vėlinių) diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-24", "O"), Name: "Šv. Kūčios"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Šv. Kalėdos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Šv. Kalėdos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Naujųjų metų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-16", "O"), Name: "Lietuvos valstybės atkūrimo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-03-11", "O"), Name: "Lietuvos nepriklausomybės atkūrimo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-16", "O"), Name: "Šv. Velykos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Antroji šv. Velykų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Tarptautinė darbo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-07", "O"), Name: "Motinos diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-04", "O"), Name: "Tėvo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-24", "O"), Name: "Rasos ir Joninių diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-07-06", "O"), Name: "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) ir Tautiškos giesmės diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-15", "O"), Name: "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-01", "O"), Name: "Visų šventųjų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-02", "O"), Name: "Mirusiųjų atminimo (Vėlinių) diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-24", "O"), Name: "Šv. Kūčios"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Šv. Kalėdos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Šv. Kalėdos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Naujųjų metų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-16", "O"), Name: "Lietuvos valstybės atkūrimo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-11", "O"), Name: "Lietuvos nepriklausomybės atkūrimo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-01", "O"), Name: "Šv. Velykos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Antroji šv. Velykų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Tarptautinė darbo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-06", "O"), Name: "Motinos diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-03", "O"), Name: "Tėvo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-24", "O"), Name: "Rasos ir Joninių diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-07-06", "O"), Name: "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) ir Tautiškos giesmės diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-15", "O"), Name: "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-01", "O"), Name: "Visų šventųjų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-02", "O"), Name: "Mirusiųjų atminimo (Vėlinių) diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-24", "O"), Name: "Šv. Kūčios"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Šv. Kalėdos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Šv. Kalėdos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Naujųjų metų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-02-16", "O"), Name: "Lietuvos valstybės atkūrimo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-11", "O"), Name: "Lietuvos nepriklausomybės atkūrimo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-21", "O"), Name: "Šv. Velykos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Antroji šv. Velykų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Tarptautinė darbo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-05", "O"), Name: "Motinos diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-02", "O"), Name: "Tėvo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-24", "O"), Name: "Rasos ir Joninių diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-07-06", "O"), Name: "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) ir Tautiškos giesmės diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-15", "O"), Name: "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-01", "O"), Name: "Visų šventųjų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-02", "O"), Name: "Mirusiųjų atminimo (Vėlinių) diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-24", "O"), Name: "Šv. Kūčios"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Šv. Kalėdos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Šv. Kalėdos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Naujųjų metų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-16", "O"), Name: "Lietuvos valstybės atkūrimo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-03-11", "O"), Name: "Lietuvos nepriklausomybės atkūrimo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-13", "O"), Name: "Šv. Velykos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Antroji šv. Velykų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Tarptautinė darbo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-04", "O"), Name: "Motinos diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-01", "O"), Name: "Tėvo diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-24", "O"), Name: "Rasos ir Joninių diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-07-06", "O"), Name: "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) ir Tautiškos giesmės diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-15", "O"), Name: "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-01", "O"), Name: "Visų šventųjų diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-02", "O"), Name: "Mirusiųjų atminimo (Vėlinių) diena"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-24", "O"), Name: "Šv. Kūčios"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Šv. Kalėdos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Šv. Kalėdos")
        };
}
