// <auto-generated>
// Baseline holiday rules for Mexico. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Mexico (<c>MX</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class MexicoCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "MX";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Mexico, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Año Nuevo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-02", "O"), Name: "Día de la Constitución"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-03-16", "O"), Name: "Natalício de Benito Juárez"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Día laboral"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-09-16", "O"), Name: "Día de la Independencia"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-01", "O"), Name: "Presidential Inauguration Holiday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-16", "O"), Name: "Día de la Revolució"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Navidad"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Año Nuevo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-02-01", "O"), Name: "Día de la Constitución"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-15", "O"), Name: "Natalício de Benito Juárez"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Día laboral"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-09-16", "O"), Name: "Día de la Independencia"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-10-01", "O"), Name: "Presidential Inauguration Holiday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-15", "O"), Name: "Día de la Revolució"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Navidad"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Año Nuevo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-07", "O"), Name: "Día de la Constitución"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-03-20", "O"), Name: "Natalício de Benito Juárez"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Día laboral"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-09-16", "O"), Name: "Día de la Independencia"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-01", "O"), Name: "Presidential Inauguration Holiday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-20", "O"), Name: "Día de la Revolució"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Navidad"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Año Nuevo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-05", "O"), Name: "Día de la Constitución"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-19", "O"), Name: "Natalício de Benito Juárez"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Día laboral"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-09-16", "O"), Name: "Día de la Independencia"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-01", "O"), Name: "Presidential Inauguration Holiday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-19", "O"), Name: "Día de la Revolució"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Navidad"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Año Nuevo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-02-04", "O"), Name: "Día de la Constitución"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-18", "O"), Name: "Natalício de Benito Juárez"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Día laboral"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-09-16", "O"), Name: "Día de la Independencia"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-10-01", "O"), Name: "Presidential Inauguration Holiday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-18", "O"), Name: "Día de la Revolució"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Navidad"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Año Nuevo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-03", "O"), Name: "Día de la Constitución"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-03-17", "O"), Name: "Natalício de Benito Juárez"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Día laboral"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-09-16", "O"), Name: "Día de la Independencia"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-10-01", "O"), Name: "Presidential Inauguration Holiday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-17", "O"), Name: "Día de la Revolució"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Navidad")
        };
}
