// <auto-generated>
// Baseline holiday rules for New Zealand. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for New Zealand (<c>NZ</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class NewZealandCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "NZ";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for New Zealand, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-02", "O"), Name: "Day After New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-06", "O"), Name: "Waitangi Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-03", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-27", "O"), Name: "ANZAC Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-01", "O"), Name: "King\'s Birthday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-07-10", "O"), Name: "Matariki"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-26", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-28", "O"), Name: "Boxing Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-04", "O"), Name: "Day After New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-02-08", "O"), Name: "Waitangi Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-26", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-04-26", "O"), Name: "ANZAC Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-07", "O"), Name: "King\'s Birthday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-25", "O"), Name: "Matariki"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-10-25", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-27", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-28", "O"), Name: "Boxing Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-03", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-04", "O"), Name: "Day After New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-07", "O"), Name: "Waitangi Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-25", "O"), Name: "ANZAC Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-05", "O"), Name: "King\'s Birthday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-07-14", "O"), Name: "Matariki"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-23", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Boxing Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-02", "O"), Name: "Day After New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-06", "O"), Name: "Waitangi Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-30", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-25", "O"), Name: "ANZAC Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-04", "O"), Name: "King\'s Birthday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-07-06", "O"), Name: "Matariki"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-22", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Boxing Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-02", "O"), Name: "Day After New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-02-06", "O"), Name: "Waitangi Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-19", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-25", "O"), Name: "ANZAC Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-03", "O"), Name: "King\'s Birthday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-21", "O"), Name: "Matariki"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-10-28", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Boxing Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-02", "O"), Name: "Day After New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-06", "O"), Name: "Waitangi Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-25", "O"), Name: "ANZAC Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-02", "O"), Name: "King\'s Birthday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-07-11", "O"), Name: "Matariki"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-10-27", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Boxing Day")
        };
}
