// <auto-generated>
// Baseline holiday rules for Poland. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Poland (<c>PL</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class PolandCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "PL";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Poland, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-06", "O"), Name: "Epiphany"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-05", "O"), Name: "Easter Sunday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-03", "O"), Name: "Constitution Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-24", "O"), Name: "Pentecost"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-04", "O"), Name: "Corpus Christi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-15", "O"), Name: "Assumption"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-01", "O"), Name: "All Saints"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-11", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-24", "O"), Name: "Christmas Eve"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Christmas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "St Stephen\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-06", "O"), Name: "Epiphany"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-28", "O"), Name: "Easter Sunday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-03", "O"), Name: "Constitution Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-16", "O"), Name: "Pentecost"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-27", "O"), Name: "Corpus Christi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-15", "O"), Name: "Assumption"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-01", "O"), Name: "All Saints"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-11", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-24", "O"), Name: "Christmas Eve"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Christmas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "St Stephen\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-06", "O"), Name: "Epiphany"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-16", "O"), Name: "Easter Sunday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-03", "O"), Name: "Constitution Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-04", "O"), Name: "Pentecost"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-15", "O"), Name: "Corpus Christi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-15", "O"), Name: "Assumption"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-01", "O"), Name: "All Saints"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-11", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-24", "O"), Name: "Christmas Eve"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Christmas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "St Stephen\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-06", "O"), Name: "Epiphany"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-01", "O"), Name: "Easter Sunday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-03", "O"), Name: "Constitution Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-20", "O"), Name: "Pentecost"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-31", "O"), Name: "Corpus Christi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-15", "O"), Name: "Assumption"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-01", "O"), Name: "All Saints"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-11", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-24", "O"), Name: "Christmas Eve"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Christmas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "St Stephen\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-06", "O"), Name: "Epiphany"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-21", "O"), Name: "Easter Sunday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-03", "O"), Name: "Constitution Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-09", "O"), Name: "Pentecost"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-20", "O"), Name: "Corpus Christi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-15", "O"), Name: "Assumption"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-01", "O"), Name: "All Saints"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-11", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-24", "O"), Name: "Christmas Eve"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Christmas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "St Stephen\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-06", "O"), Name: "Epiphany"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-13", "O"), Name: "Easter Sunday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Easter Monday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Labour Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-03", "O"), Name: "Constitution Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-01", "O"), Name: "Pentecost"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-12", "O"), Name: "Corpus Christi"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-15", "O"), Name: "Assumption"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-01", "O"), Name: "All Saints"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-11", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-24", "O"), Name: "Christmas Eve"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Christmas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "St Stephen\'s Day")
        };
}
