// <auto-generated>
// Baseline holiday rules for Portugal. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Portugal (<c>PT</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class PortugalCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "PT";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Portugal, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Ano Novo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-17", "O"), Name: "Carnaval"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-03", "O"), Name: "Sexta-feira Santa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-05", "O"), Name: "Domingo de Páscoa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-25", "O"), Name: "Dia da Liberdade"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Dia do Trabalhador"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-04", "O"), Name: "Corpo de Deus"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-10", "O"), Name: "Dia de Portugal, de Camões e das Comunidades Portuguesas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-15", "O"), Name: "Assunção de Nossa Senhora"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-05", "O"), Name: "Implantação da República"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-01", "O"), Name: "Dia de Todos-os-Santos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-01", "O"), Name: "Restauração da Independência"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-08", "O"), Name: "Imaculada Conceição"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Natal"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Ano Novo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-02-09", "O"), Name: "Carnaval"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-26", "O"), Name: "Sexta-feira Santa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-28", "O"), Name: "Domingo de Páscoa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-04-25", "O"), Name: "Dia da Liberdade"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Dia do Trabalhador"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-27", "O"), Name: "Corpo de Deus"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-10", "O"), Name: "Dia de Portugal, de Camões e das Comunidades Portuguesas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-15", "O"), Name: "Assunção de Nossa Senhora"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-10-05", "O"), Name: "Implantação da República"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-01", "O"), Name: "Dia de Todos-os-Santos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-01", "O"), Name: "Restauração da Independência"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-08", "O"), Name: "Imaculada Conceição"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Natal"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Ano Novo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-29", "O"), Name: "Carnaval"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Sexta-feira Santa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-16", "O"), Name: "Domingo de Páscoa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-25", "O"), Name: "Dia da Liberdade"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Dia do Trabalhador"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-10", "O"), Name: "Dia de Portugal, de Camões e das Comunidades Portuguesas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-15", "O"), Name: "Corpo de Deus"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-15", "O"), Name: "Assunção de Nossa Senhora"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-05", "O"), Name: "Implantação da República"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-01", "O"), Name: "Dia de Todos-os-Santos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-01", "O"), Name: "Restauração da Independência"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-08", "O"), Name: "Imaculada Conceição"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Natal"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Ano Novo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-13", "O"), Name: "Carnaval"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-30", "O"), Name: "Sexta-feira Santa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-01", "O"), Name: "Domingo de Páscoa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-25", "O"), Name: "Dia da Liberdade"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Dia do Trabalhador"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-31", "O"), Name: "Corpo de Deus"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-10", "O"), Name: "Dia de Portugal, de Camões e das Comunidades Portuguesas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-15", "O"), Name: "Assunção de Nossa Senhora"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-05", "O"), Name: "Implantação da República"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-01", "O"), Name: "Dia de Todos-os-Santos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-01", "O"), Name: "Restauração da Independência"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-08", "O"), Name: "Imaculada Conceição"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Natal"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Ano Novo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-05", "O"), Name: "Carnaval"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-19", "O"), Name: "Sexta-feira Santa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-21", "O"), Name: "Domingo de Páscoa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-25", "O"), Name: "Dia da Liberdade"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Dia do Trabalhador"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-10", "O"), Name: "Dia de Portugal, de Camões e das Comunidades Portuguesas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-20", "O"), Name: "Corpo de Deus"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-15", "O"), Name: "Assunção de Nossa Senhora"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-10-05", "O"), Name: "Implantação da República"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-01", "O"), Name: "Dia de Todos-os-Santos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-01", "O"), Name: "Restauração da Independência"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-08", "O"), Name: "Imaculada Conceição"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Natal"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Ano Novo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-25", "O"), Name: "Carnaval"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Sexta-feira Santa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-13", "O"), Name: "Domingo de Páscoa"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-25", "O"), Name: "Dia da Liberdade"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Dia do Trabalhador"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-10", "O"), Name: "Dia de Portugal, de Camões e das Comunidades Portuguesas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-12", "O"), Name: "Corpo de Deus"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-15", "O"), Name: "Assunção de Nossa Senhora"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-10-05", "O"), Name: "Implantação da República"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-01", "O"), Name: "Dia de Todos-os-Santos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-01", "O"), Name: "Restauração da Independência"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-08", "O"), Name: "Imaculada Conceição"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Natal")
        };
}
