// <auto-generated>
// Baseline holiday rules for Romania. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Romania (<c>RO</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class RomaniaCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "RO";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Romania, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Anul nou"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-02", "O"), Name: "Anul nou"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-06", "O"), Name: "Bobotează"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-07", "O"), Name: "Sfântul Ion"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-24", "O"), Name: "Unirea Principatelor Române"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-10", "O"), Name: "Vinerea Mare"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-12", "O"), Name: "Paștele"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-13", "O"), Name: "Paștele"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Ziua Muncii"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-31", "O"), Name: "Rusaliile"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-01", "O"), Name: "Ziua Copilului"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-15", "O"), Name: "Sfânta Maria Mare"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-30", "O"), Name: "Sfântul Andrei"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-01", "O"), Name: "Ziua Națională a României"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Crăciunul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Crăciunul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Anul nou"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-02", "O"), Name: "Anul nou"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-06", "O"), Name: "Bobotează"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-07", "O"), Name: "Sfântul Ion"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-24", "O"), Name: "Unirea Principatelor Române"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-04-30", "O"), Name: "Vinerea Mare"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Ziua Muncii"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-02", "O"), Name: "Paștele"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-03", "O"), Name: "Paștele"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-01", "O"), Name: "Ziua Copilului"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-20", "O"), Name: "Rusaliile"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-21", "O"), Name: "Rusaliile"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-15", "O"), Name: "Sfânta Maria Mare"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-30", "O"), Name: "Sfântul Andrei"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-01", "O"), Name: "Ziua Națională a României"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Crăciunul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Crăciunul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Anul nou"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-02", "O"), Name: "Anul nou"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-06", "O"), Name: "Bobotează"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-07", "O"), Name: "Sfântul Ion"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-24", "O"), Name: "Unirea Principatelor Române"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Vinerea Mare"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-16", "O"), Name: "Paștele"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Paștele"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Ziua Muncii"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-01", "O"), Name: "Ziua Copilului"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-04", "O"), Name: "Rusaliile"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-05", "O"), Name: "Rusaliile"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-15", "O"), Name: "Sfânta Maria Mare"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-30", "O"), Name: "Sfântul Andrei"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-01", "O"), Name: "Ziua Națională a României"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Crăciunul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Crăciunul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Anul nou"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-02", "O"), Name: "Anul nou"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-06", "O"), Name: "Bobotează"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-07", "O"), Name: "Sfântul Ion"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-24", "O"), Name: "Unirea Principatelor Române"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-06", "O"), Name: "Vinerea Mare"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-08", "O"), Name: "Paștele"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-09", "O"), Name: "Paștele"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Ziua Muncii"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-27", "O"), Name: "Rusaliile"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-28", "O"), Name: "Rusaliile"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-01", "O"), Name: "Ziua Copilului"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-15", "O"), Name: "Sfânta Maria Mare"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-30", "O"), Name: "Sfântul Andrei"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-01", "O"), Name: "Ziua Națională a României"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Crăciunul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Crăciunul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Anul nou"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-02", "O"), Name: "Anul nou"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-06", "O"), Name: "Bobotează"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-07", "O"), Name: "Sfântul Ion"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-24", "O"), Name: "Unirea Principatelor Române"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-26", "O"), Name: "Vinerea Mare"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-28", "O"), Name: "Paștele"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-29", "O"), Name: "Paștele"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Ziua Muncii"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-01", "O"), Name: "Ziua Copilului"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-16", "O"), Name: "Rusaliile"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-17", "O"), Name: "Rusaliile"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-15", "O"), Name: "Sfânta Maria Mare"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-30", "O"), Name: "Sfântul Andrei"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-01", "O"), Name: "Ziua Națională a României"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Crăciunul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Crăciunul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Anul nou"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-02", "O"), Name: "Anul nou"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-06", "O"), Name: "Bobotează"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-07", "O"), Name: "Sfântul Ion"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-24", "O"), Name: "Unirea Principatelor Române"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Vinerea Mare"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-13", "O"), Name: "Paștele"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Paștele"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Ziua Muncii"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-01", "O"), Name: "Ziua Copilului"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-02", "O"), Name: "Rusaliile"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-15", "O"), Name: "Sfânta Maria Mare"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-30", "O"), Name: "Sfântul Andrei"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-01", "O"), Name: "Ziua Națională a României"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Crăciunul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Crăciunul")
        };
}
