// <auto-generated>
// Baseline holiday rules for Serbia. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Serbia (<c>RS</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class SerbiaCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "RS";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Serbia, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Нова година"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-02", "O"), Name: "Нова година"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-07", "O"), Name: "Божић"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-15", "O"), Name: "Дан државности Србије"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-16", "O"), Name: "Дан државности Србије"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-10", "O"), Name: "Велики петак"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-12", "O"), Name: "Васкрс"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-13", "O"), Name: "Васкрсни понедељак"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Празник рада"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-02", "O"), Name: "Празник рада"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-11", "O"), Name: "Дан примирја"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Нова година"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-02", "O"), Name: "Нова година"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-07", "O"), Name: "Божић"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-02-15", "O"), Name: "Дан државности Србије"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-02-16", "O"), Name: "Дан државности Србије"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-04-30", "O"), Name: "Велики петак"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Празник рада"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-02", "O"), Name: "Празник рада"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-03", "O"), Name: "Васкрсни понедељак"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-11", "O"), Name: "Дан примирја"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Нова година"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-02", "O"), Name: "Нова година"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-07", "O"), Name: "Божић"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-15", "O"), Name: "Дан државности Србије"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-16", "O"), Name: "Дан државности Србије"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Велики петак"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-16", "O"), Name: "Васкрс"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Васкрсни понедељак"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Празник рада"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-02", "O"), Name: "Празник рада"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-11", "O"), Name: "Дан примирја"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Нова година"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-02", "O"), Name: "Нова година"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-07", "O"), Name: "Божић"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-15", "O"), Name: "Дан државности Србије"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-16", "O"), Name: "Дан државности Србије"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-06", "O"), Name: "Велики петак"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-08", "O"), Name: "Васкрс"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-09", "O"), Name: "Васкрсни понедељак"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Празник рада"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-02", "O"), Name: "Празник рада"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-11", "O"), Name: "Дан примирја"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Нова година"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-02", "O"), Name: "Нова година"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-07", "O"), Name: "Божић"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-02-15", "O"), Name: "Дан државности Србије"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-02-16", "O"), Name: "Дан државности Србије"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-26", "O"), Name: "Велики петак"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-28", "O"), Name: "Васкрс"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-29", "O"), Name: "Васкрсни понедељак"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Празник рада"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-02", "O"), Name: "Празник рада"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-11", "O"), Name: "Дан примирја"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Нова година"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-02", "O"), Name: "Нова година"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-07", "O"), Name: "Божић"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-15", "O"), Name: "Дан државности Србије"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-16", "O"), Name: "Дан државности Србије"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Велики петак"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-13", "O"), Name: "Васкрс"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Васкрсни понедељак"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Празник рада"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-02", "O"), Name: "Празник рада"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-11", "O"), Name: "Дан примирја")
        };
}
