// <auto-generated>
// Baseline holiday rules for Slovakia. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Slovakia (<c>SK</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class SlovakiaCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "SK";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Slovakia, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Deň vzniku Slovenskej republiky"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-06", "O"), Name: "Zjavenie Pána (Traja králi)"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-03", "O"), Name: "Veľký piatok"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Veľkonočný pondelok"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Sviatok práce"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-08", "O"), Name: "Deň víťazstva nad fašizmom"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-07-05", "O"), Name: "Sviatok svätého Cyrila a Metoda"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-29", "O"), Name: "Výročie SNP"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-09-01", "O"), Name: "Deň Ústavy Slovenskej republiky"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-09-15", "O"), Name: "Sedembolestná Panna Mária"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-01", "O"), Name: "Sviatok všetkých svätých"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-17", "O"), Name: "Deň boja za slobodu a demokraciu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-24", "O"), Name: "Štedrý deň"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Prvý sviatok vianočný"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Druhý sviatok vianočný"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Deň vzniku Slovenskej republiky"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-06", "O"), Name: "Zjavenie Pána (Traja králi)"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-26", "O"), Name: "Veľký piatok"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Veľkonočný pondelok"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Sviatok práce"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-08", "O"), Name: "Deň víťazstva nad fašizmom"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-07-05", "O"), Name: "Sviatok svätého Cyrila a Metoda"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-29", "O"), Name: "Výročie SNP"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-09-01", "O"), Name: "Deň Ústavy Slovenskej republiky"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-09-15", "O"), Name: "Sedembolestná Panna Mária"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-01", "O"), Name: "Sviatok všetkých svätých"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-17", "O"), Name: "Deň boja za slobodu a demokraciu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-24", "O"), Name: "Štedrý deň"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Prvý sviatok vianočný"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Druhý sviatok vianočný"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Deň vzniku Slovenskej republiky"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-06", "O"), Name: "Zjavenie Pána (Traja králi)"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Veľký piatok"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Veľkonočný pondelok"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Sviatok práce"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-08", "O"), Name: "Deň víťazstva nad fašizmom"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-07-05", "O"), Name: "Sviatok svätého Cyrila a Metoda"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-29", "O"), Name: "Výročie SNP"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-09-01", "O"), Name: "Deň Ústavy Slovenskej republiky"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-09-15", "O"), Name: "Sedembolestná Panna Mária"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-01", "O"), Name: "Sviatok všetkých svätých"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-17", "O"), Name: "Deň boja za slobodu a demokraciu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-24", "O"), Name: "Štedrý deň"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Prvý sviatok vianočný"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Druhý sviatok vianočný"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Deň vzniku Slovenskej republiky"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-06", "O"), Name: "Zjavenie Pána (Traja králi)"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-30", "O"), Name: "Veľký piatok"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Veľkonočný pondelok"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Sviatok práce"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-08", "O"), Name: "Deň víťazstva nad fašizmom"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-07-05", "O"), Name: "Sviatok svätého Cyrila a Metoda"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-29", "O"), Name: "Výročie SNP"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-09-01", "O"), Name: "Deň Ústavy Slovenskej republiky"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-09-15", "O"), Name: "Sedembolestná Panna Mária"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-01", "O"), Name: "Sviatok všetkých svätých"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-17", "O"), Name: "Deň boja za slobodu a demokraciu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-24", "O"), Name: "Štedrý deň"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Prvý sviatok vianočný"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Druhý sviatok vianočný"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Deň vzniku Slovenskej republiky"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-06", "O"), Name: "Zjavenie Pána (Traja králi)"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-19", "O"), Name: "Veľký piatok"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Veľkonočný pondelok"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Sviatok práce"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-08", "O"), Name: "Deň víťazstva nad fašizmom"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-07-05", "O"), Name: "Sviatok svätého Cyrila a Metoda"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-29", "O"), Name: "Výročie SNP"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-09-01", "O"), Name: "Deň Ústavy Slovenskej republiky"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-09-15", "O"), Name: "Sedembolestná Panna Mária"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-01", "O"), Name: "Sviatok všetkých svätých"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-17", "O"), Name: "Deň boja za slobodu a demokraciu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-24", "O"), Name: "Štedrý deň"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Prvý sviatok vianočný"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Druhý sviatok vianočný"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Deň vzniku Slovenskej republiky"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-06", "O"), Name: "Zjavenie Pána (Traja králi)"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Veľký piatok"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Veľkonočný pondelok"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Sviatok práce"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-08", "O"), Name: "Deň víťazstva nad fašizmom"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-07-05", "O"), Name: "Sviatok svätého Cyrila a Metoda"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-29", "O"), Name: "Výročie SNP"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-09-01", "O"), Name: "Deň Ústavy Slovenskej republiky"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-09-15", "O"), Name: "Sedembolestná Panna Mária"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-01", "O"), Name: "Sviatok všetkých svätých"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-17", "O"), Name: "Deň boja za slobodu a demokraciu"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-24", "O"), Name: "Štedrý deň"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Prvý sviatok vianočný"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Druhý sviatok vianočný")
        };
}
