// <auto-generated>
// Baseline holiday rules for Slovenia. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Slovenia (<c>SI</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class SloveniaCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "SI";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Slovenia, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Novo leto, prvi januar"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-02", "O"), Name: "Novo leto, drugi januar"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-08", "O"), Name: "Prešernov dan"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Velikonočni ponedeljek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-27", "O"), Name: "Dan upora proti okupatorju"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Dan dela 1.maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-02", "O"), Name: "Dan dela 1.maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-25", "O"), Name: "Dan državnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-15", "O"), Name: "Marijino vnebovzetje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-31", "O"), Name: "Dan reformacije"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-01", "O"), Name: "Dan spomina na mrtve"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Božič"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Day suverenosti in enotnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Novo leto, prvi januar"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-02", "O"), Name: "Novo leto, drugi januar"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-02-08", "O"), Name: "Prešernov dan"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Velikonočni ponedeljek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-04-27", "O"), Name: "Dan upora proti okupatorju"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Dan dela 1.maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-02", "O"), Name: "Dan dela 1.maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-25", "O"), Name: "Dan državnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-15", "O"), Name: "Marijino vnebovzetje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-10-31", "O"), Name: "Dan reformacije"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-01", "O"), Name: "Dan spomina na mrtve"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Božič"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Day suverenosti in enotnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Novo leto, prvi januar"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-02", "O"), Name: "Novo leto, drugi januar"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-08", "O"), Name: "Prešernov dan"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Velikonočni ponedeljek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-27", "O"), Name: "Dan upora proti okupatorju"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Dan dela 1.maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-02", "O"), Name: "Dan dela 1.maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-25", "O"), Name: "Dan državnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-15", "O"), Name: "Marijino vnebovzetje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-31", "O"), Name: "Dan reformacije"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-01", "O"), Name: "Dan spomina na mrtve"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Božič"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Day suverenosti in enotnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Novo leto, prvi januar"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-02", "O"), Name: "Novo leto, drugi januar"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-08", "O"), Name: "Prešernov dan"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Velikonočni ponedeljek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-27", "O"), Name: "Dan upora proti okupatorju"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Dan dela 1.maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-02", "O"), Name: "Dan dela 1.maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-25", "O"), Name: "Dan državnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-15", "O"), Name: "Marijino vnebovzetje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-31", "O"), Name: "Dan reformacije"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-01", "O"), Name: "Dan spomina na mrtve"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Božič"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Day suverenosti in enotnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Novo leto, prvi januar"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-02", "O"), Name: "Novo leto, drugi januar"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-02-08", "O"), Name: "Prešernov dan"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Velikonočni ponedeljek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-27", "O"), Name: "Dan upora proti okupatorju"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Dan dela 1.maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-02", "O"), Name: "Dan dela 1.maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-25", "O"), Name: "Dan državnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-15", "O"), Name: "Marijino vnebovzetje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-10-31", "O"), Name: "Dan reformacije"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-01", "O"), Name: "Dan spomina na mrtve"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Božič"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Day suverenosti in enotnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Novo leto, prvi januar"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-02", "O"), Name: "Novo leto, drugi januar"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-08", "O"), Name: "Prešernov dan"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Velikonočni ponedeljek"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-27", "O"), Name: "Dan upora proti okupatorju"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Dan dela 1.maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-02", "O"), Name: "Dan dela 1.maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-25", "O"), Name: "Dan državnosti"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-15", "O"), Name: "Marijino vnebovzetje"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-10-31", "O"), Name: "Dan reformacije"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-01", "O"), Name: "Dan spomina na mrtve"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Božič"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Day suverenosti in enotnosti")
        };
}
