// <auto-generated>
// Baseline holiday rules for South Africa. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for South Africa (<c>ZA</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class SouthAfricaCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "ZA";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for South Africa, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-03-21", "O"), Name: "Human Rights Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-03", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Family Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-27", "O"), Name: "Freedom Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Workers\' Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-16", "O"), Name: "Youth Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-10", "O"), Name: "National Women\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-09-24", "O"), Name: "Heritage Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-16", "O"), Name: "Day of Reconciliation"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Day of Goodwill"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-22", "O"), Name: "Human Rights Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-26", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Family Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-04-27", "O"), Name: "Freedom Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Workers\' Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-16", "O"), Name: "Youth Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-09", "O"), Name: "National Women\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-09-24", "O"), Name: "Heritage Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-16", "O"), Name: "Day of Reconciliation"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-27", "O"), Name: "Day of Goodwill"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-03-21", "O"), Name: "Human Rights Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Family Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-27", "O"), Name: "Freedom Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Workers\' Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-16", "O"), Name: "Youth Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-09", "O"), Name: "National Women\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-09-25", "O"), Name: "Heritage Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-16", "O"), Name: "Day of Reconciliation"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Day of Goodwill"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-21", "O"), Name: "Human Rights Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-30", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Family Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-27", "O"), Name: "Freedom Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Workers\' Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-16", "O"), Name: "Youth Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-09", "O"), Name: "National Women\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-09-24", "O"), Name: "Heritage Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-17", "O"), Name: "Day of Reconciliation"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Day of Goodwill"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-03-21", "O"), Name: "Human Rights Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-19", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Family Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-27", "O"), Name: "Freedom Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Workers\' Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-17", "O"), Name: "Youth Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-09", "O"), Name: "National Women\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-09-24", "O"), Name: "Heritage Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-16", "O"), Name: "Day of Reconciliation"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Day of Goodwill"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-03-21", "O"), Name: "Human Rights Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Good Friday"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Family Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-28", "O"), Name: "Freedom Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Workers\' Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-16", "O"), Name: "Youth Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-09", "O"), Name: "National Women\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-09-24", "O"), Name: "Heritage Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-16", "O"), Name: "Day of Reconciliation"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Christmas Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Day of Goodwill")
        };
}
