// <auto-generated>
// Baseline holiday rules for Spain. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Spain (<c>ES</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class SpainCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "ES";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Spain, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Año Nuevo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-06", "O"), Name: "Epifanía"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-03", "O"), Name: "Viernes Santo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Día del Trabajador"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-15", "O"), Name: "Asunción"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-12", "O"), Name: "Fiesta Nacional de España"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-01", "O"), Name: "Día de todos los Santos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-06", "O"), Name: "Día de la Constitución"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-08", "O"), Name: "Inmaculada Concepción"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Navidad"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Año Nuevo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-06", "O"), Name: "Epifanía"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-26", "O"), Name: "Viernes Santo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Día del Trabajador"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-15", "O"), Name: "Asunción"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-10-12", "O"), Name: "Fiesta Nacional de España"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-01", "O"), Name: "Día de todos los Santos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-06", "O"), Name: "Día de la Constitución"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-08", "O"), Name: "Inmaculada Concepción"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Navidad"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Año Nuevo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-06", "O"), Name: "Epifanía"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Viernes Santo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Día del Trabajador"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-15", "O"), Name: "Asunción"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-12", "O"), Name: "Fiesta Nacional de España"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-01", "O"), Name: "Día de todos los Santos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-06", "O"), Name: "Día de la Constitución"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-08", "O"), Name: "Inmaculada Concepción"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Navidad"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Año Nuevo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-06", "O"), Name: "Epifanía"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-30", "O"), Name: "Viernes Santo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Día del Trabajador"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-15", "O"), Name: "Asunción"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-12", "O"), Name: "Fiesta Nacional de España"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-01", "O"), Name: "Día de todos los Santos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-06", "O"), Name: "Día de la Constitución"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-08", "O"), Name: "Inmaculada Concepción"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Navidad"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Año Nuevo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-06", "O"), Name: "Epifanía"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-19", "O"), Name: "Viernes Santo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Día del Trabajador"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-15", "O"), Name: "Asunción"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-10-12", "O"), Name: "Fiesta Nacional de España"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-01", "O"), Name: "Día de todos los Santos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-06", "O"), Name: "Día de la Constitución"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-08", "O"), Name: "Inmaculada Concepción"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Navidad"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Año Nuevo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-06", "O"), Name: "Epifanía"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Viernes Santo"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Día del Trabajador"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-15", "O"), Name: "Asunción"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-10-12", "O"), Name: "Fiesta Nacional de España"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-01", "O"), Name: "Día de todos los Santos"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-06", "O"), Name: "Día de la Constitución"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-08", "O"), Name: "Inmaculada Concepción"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Navidad")
        };
}
