// <auto-generated>
// Baseline holiday rules for Sweden. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Sweden (<c>SE</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class SwedenCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "SE";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Sweden, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Nyårsdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-06", "O"), Name: "Trettondag jul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-03", "O"), Name: "Långfredag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-05", "O"), Name: "Påskdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-06", "O"), Name: "Annandag påsk"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Första maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-14", "O"), Name: "Kristi himmelfärds dag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-24", "O"), Name: "Pingstdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-06", "O"), Name: "Nationaldagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-19", "O"), Name: "Midsommarafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-20", "O"), Name: "Midsommardagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-31", "O"), Name: "Alla helgons dag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-24", "O"), Name: "Julafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Juldagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-26", "O"), Name: "Annandag jul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-31", "O"), Name: "Nyårsafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Nyårsdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-06", "O"), Name: "Trettondag jul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-26", "O"), Name: "Långfredag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-28", "O"), Name: "Påskdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-29", "O"), Name: "Annandag påsk"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Första maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-06", "O"), Name: "Kristi himmelfärds dag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-16", "O"), Name: "Pingstdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-06", "O"), Name: "Nationaldagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-25", "O"), Name: "Midsommarafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-26", "O"), Name: "Midsommardagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-06", "O"), Name: "Alla helgons dag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-24", "O"), Name: "Julafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-25", "O"), Name: "Juldagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-26", "O"), Name: "Annandag jul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-31", "O"), Name: "Nyårsafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Nyårsdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-06", "O"), Name: "Trettondag jul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-14", "O"), Name: "Långfredag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-16", "O"), Name: "Påskdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-17", "O"), Name: "Annandag påsk"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Första maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-25", "O"), Name: "Kristi himmelfärds dag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-04", "O"), Name: "Pingstdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-06", "O"), Name: "Nationaldagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-23", "O"), Name: "Midsommarafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-24", "O"), Name: "Midsommardagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-04", "O"), Name: "Alla helgons dag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-24", "O"), Name: "Julafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Juldagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-26", "O"), Name: "Annandag jul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-31", "O"), Name: "Nyårsafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Nyårsdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-06", "O"), Name: "Trettondag jul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-03-30", "O"), Name: "Långfredag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-01", "O"), Name: "Påskdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-02", "O"), Name: "Annandag påsk"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Första maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-10", "O"), Name: "Kristi himmelfärds dag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-20", "O"), Name: "Pingstdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-06", "O"), Name: "Nationaldagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-22", "O"), Name: "Midsommarafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-23", "O"), Name: "Midsommardagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-03", "O"), Name: "Alla helgons dag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-24", "O"), Name: "Julafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Juldagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-26", "O"), Name: "Annandag jul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-31", "O"), Name: "Nyårsafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Nyårsdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-06", "O"), Name: "Trettondag jul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-19", "O"), Name: "Långfredag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-21", "O"), Name: "Påskdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-22", "O"), Name: "Annandag påsk"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Första maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-30", "O"), Name: "Kristi himmelfärds dag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-06", "O"), Name: "Nationaldagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-09", "O"), Name: "Pingstdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-21", "O"), Name: "Midsommarafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-22", "O"), Name: "Midsommardagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-02", "O"), Name: "Alla helgons dag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-24", "O"), Name: "Julafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Juldagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-26", "O"), Name: "Annandag jul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-31", "O"), Name: "Nyårsafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Nyårsdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-06", "O"), Name: "Trettondag jul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-11", "O"), Name: "Långfredag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-13", "O"), Name: "Påskdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-14", "O"), Name: "Annandag påsk"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Första maj"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-22", "O"), Name: "Kristi himmelfärds dag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-01", "O"), Name: "Pingstdagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-06", "O"), Name: "Nationaldagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-20", "O"), Name: "Midsommarafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-21", "O"), Name: "Midsommardagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-01", "O"), Name: "Alla helgons dag"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-24", "O"), Name: "Julafton"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Juldagen"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-26", "O"), Name: "Annandag jul"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-31", "O"), Name: "Nyårsafton")
        };
}
