// <auto-generated>
// Baseline holiday rules for Turkey. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for Turkey (<c>TR</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class TurkeyCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "TR";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for Turkey, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "Yılbaşı Tatili"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-03-20", "O"), Name: "Ramazan Bayramı 1. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-03-21", "O"), Name: "Ramazan Bayramı 2. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-03-22", "O"), Name: "Ramazan Bayramı 3. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-04-23", "O"), Name: "Ulusal Egemenlik ve Çocuk Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-01", "O"), Name: "Emek ve Dayanışma Günü"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-19", "O"), Name: "Atatürk’ü Anma, Gençlik ve Spor Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-27", "O"), Name: "Kurban Bayramı 1. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-28", "O"), Name: "Kurban Bayramı 2. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-29", "O"), Name: "Kurban Bayramı 3. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-30", "O"), Name: "Kurban Bayramı 4. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-07-15", "O"), Name: "Demokrasi ve Milli Birlik Günü"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-08-30", "O"), Name: "Zafer Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-29", "O"), Name: "Cumhuriyet Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "Yılbaşı Tatili"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-09", "O"), Name: "Ramazan Bayramı 1. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-10", "O"), Name: "Ramazan Bayramı 2. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-03-11", "O"), Name: "Ramazan Bayramı 3. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-04-23", "O"), Name: "Ulusal Egemenlik ve Çocuk Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-01", "O"), Name: "Emek ve Dayanışma Günü"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-16", "O"), Name: "Kurban Bayramı 1. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-17", "O"), Name: "Kurban Bayramı 2. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-18", "O"), Name: "Kurban Bayramı 3. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-19", "O"), Name: "Atatürk’ü Anma, Gençlik ve Spor Bayramı, Kurban Bayramı 4. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-07-15", "O"), Name: "Demokrasi ve Milli Birlik Günü"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-08-30", "O"), Name: "Zafer Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-10-29", "O"), Name: "Cumhuriyet Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-01", "O"), Name: "Yılbaşı Tatili"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-26", "O"), Name: "Ramazan Bayramı 1. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-27", "O"), Name: "Ramazan Bayramı 2. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-28", "O"), Name: "Ramazan Bayramı 3. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-04-23", "O"), Name: "Ulusal Egemenlik ve Çocuk Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-01", "O"), Name: "Emek ve Dayanışma Günü"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-05", "O"), Name: "Kurban Bayramı 1. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-06", "O"), Name: "Kurban Bayramı 2. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-07", "O"), Name: "Kurban Bayramı 3. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-08", "O"), Name: "Kurban Bayramı 4. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-19", "O"), Name: "Atatürk’ü Anma, Gençlik ve Spor Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-07-15", "O"), Name: "Demokrasi ve Milli Birlik Günü"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-08-30", "O"), Name: "Zafer Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-29", "O"), Name: "Cumhuriyet Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "Yılbaşı Tatili"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-14", "O"), Name: "Ramazan Bayramı 1. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-15", "O"), Name: "Ramazan Bayramı 2. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-16", "O"), Name: "Ramazan Bayramı 3. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-23", "O"), Name: "Ulusal Egemenlik ve Çocuk Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-24", "O"), Name: "Kurban Bayramı 1. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-25", "O"), Name: "Kurban Bayramı 2. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-26", "O"), Name: "Kurban Bayramı 3. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-04-27", "O"), Name: "Kurban Bayramı 4. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-01", "O"), Name: "Emek ve Dayanışma Günü"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-19", "O"), Name: "Atatürk’ü Anma, Gençlik ve Spor Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-07-15", "O"), Name: "Demokrasi ve Milli Birlik Günü"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-08-30", "O"), Name: "Zafer Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-29", "O"), Name: "Cumhuriyet Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "Yılbaşı Tatili"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-02-04", "O"), Name: "Ramazan Bayramı 1. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-02-05", "O"), Name: "Ramazan Bayramı 2. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-02-06", "O"), Name: "Ramazan Bayramı 3. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-13", "O"), Name: "Kurban Bayramı 1. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-14", "O"), Name: "Kurban Bayramı 2. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-15", "O"), Name: "Kurban Bayramı 3. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-16", "O"), Name: "Kurban Bayramı 4. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-04-23", "O"), Name: "Ulusal Egemenlik ve Çocuk Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-01", "O"), Name: "Emek ve Dayanışma Günü"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-19", "O"), Name: "Atatürk’ü Anma, Gençlik ve Spor Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-07-15", "O"), Name: "Demokrasi ve Milli Birlik Günü"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-08-30", "O"), Name: "Zafer Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-10-29", "O"), Name: "Cumhuriyet Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "Yılbaşı Tatili"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-24", "O"), Name: "Ramazan Bayramı 1. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-25", "O"), Name: "Ramazan Bayramı 2. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-26", "O"), Name: "Ramazan Bayramı 3. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-02", "O"), Name: "Kurban Bayramı 1. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-03", "O"), Name: "Kurban Bayramı 2. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-04", "O"), Name: "Kurban Bayramı 3. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-05", "O"), Name: "Kurban Bayramı 4. Gün"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-04-23", "O"), Name: "Ulusal Egemenlik ve Çocuk Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-01", "O"), Name: "Emek ve Dayanışma Günü"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-19", "O"), Name: "Atatürk’ü Anma, Gençlik ve Spor Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-07-15", "O"), Name: "Demokrasi ve Milli Birlik Günü"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-08-30", "O"), Name: "Zafer Bayramı"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-10-29", "O"), Name: "Cumhuriyet Bayramı")
        };
}
