// <auto-generated>
// Baseline holiday rules for United States. Regenerated by tools/GeneratePublicHolidays.
// Source: PublicHoliday 3.16.0.0. Years 2026 through 2031.
// </auto-generated>

namespace Novolis.Time.Workday;

/// <summary>
/// Baseline public-holiday rules for United States (<c>US</c>),
/// 2026 through 2031.
/// These rules are defaults so sparse <see cref="CalendarOverride"/> configuration can replace or clear one date
/// without rewriting the rest of the collection.
/// </summary>
public static class UnitedStatesCalendar
{
    /// <summary>ISO 3166-1 alpha-2 country code for this baseline.</summary>
    public const string CountryCode = "US";

    /// <summary>First calendar year included in <see cref="Baseline"/>.</summary>
    public const int FirstYear = 2026;

    /// <summary>Last calendar year included in <see cref="Baseline"/>.</summary>
    public const int LastYear = 2031;

    /// <summary>
    /// Baseline holiday rules for United States, 2026 through 2031.
    /// A date that is absent is an ordinary day. Configuration overrides one date and leaves this collection unchanged.
    /// </summary>
    public static IReadOnlyList<PublicHolidayFact> Baseline { get; } =
        new List<PublicHolidayFact>
        {
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-01-19", "O"), Name: "Martin Luther King Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-02-16", "O"), Name: "President\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-05-25", "O"), Name: "Memorial Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-06-19", "O"), Name: "Juneteenth"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-07-03", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-09-07", "O"), Name: "Labor Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-10-12", "O"), Name: "Columbus Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-11", "O"), Name: "Veteran\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-11-26", "O"), Name: "Thanksgiving"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2026-12-25", "O"), Name: "Christmas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-01-18", "O"), Name: "Martin Luther King Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-02-15", "O"), Name: "President\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-05-31", "O"), Name: "Memorial Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-06-18", "O"), Name: "Juneteenth"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-07-05", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-09-06", "O"), Name: "Labor Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-10-11", "O"), Name: "Columbus Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-11", "O"), Name: "Veteran\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-11-25", "O"), Name: "Thanksgiving"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-24", "O"), Name: "Christmas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2027-12-31", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-01-17", "O"), Name: "Martin Luther King Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-02-21", "O"), Name: "President\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-05-29", "O"), Name: "Memorial Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-06-19", "O"), Name: "Juneteenth"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-07-04", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-09-04", "O"), Name: "Labor Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-10-09", "O"), Name: "Columbus Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-10", "O"), Name: "Veteran\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-11-23", "O"), Name: "Thanksgiving"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2028-12-25", "O"), Name: "Christmas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-01-15", "O"), Name: "Martin Luther King Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-02-19", "O"), Name: "President\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-05-28", "O"), Name: "Memorial Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-06-19", "O"), Name: "Juneteenth"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-07-04", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-09-03", "O"), Name: "Labor Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-10-08", "O"), Name: "Columbus Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-12", "O"), Name: "Veteran\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-11-22", "O"), Name: "Thanksgiving"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2029-12-25", "O"), Name: "Christmas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-01-21", "O"), Name: "Martin Luther King Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-02-18", "O"), Name: "President\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-05-27", "O"), Name: "Memorial Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-06-19", "O"), Name: "Juneteenth"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-07-04", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-09-02", "O"), Name: "Labor Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-10-14", "O"), Name: "Columbus Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-11", "O"), Name: "Veteran\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-11-28", "O"), Name: "Thanksgiving"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2030-12-25", "O"), Name: "Christmas"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-01", "O"), Name: "New Year"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-01-20", "O"), Name: "Martin Luther King Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-02-17", "O"), Name: "President\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-05-26", "O"), Name: "Memorial Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-06-19", "O"), Name: "Juneteenth"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-07-04", "O"), Name: "Independence Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-09-01", "O"), Name: "Labor Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-10-13", "O"), Name: "Columbus Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-11", "O"), Name: "Veteran\'s Day"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-11-27", "O"), Name: "Thanksgiving"),
            new PublicHolidayFact(Date: DateOnly.ParseExact("2031-12-25", "O"), Name: "Christmas")
        };
}
